export type SabatinaPriority = "manter" | "reforcar" | "urgente";

export type RealSabatinaQuestion = {
  id: string;
  week: number;
  topic: string;
  question: string;
  priority: SabatinaPriority;
  answer: string;
  reasoning: string;
  banking: string;
  watchOut: string;
};

const q = (
  id: string,
  week: number,
  topic: string,
  question: string,
  priority: SabatinaPriority,
  answer: string,
  reasoning: string,
  banking: string,
  watchOut: string,
): RealSabatinaQuestion => ({ id, week, topic, question, priority, answer, reasoning, banking, watchOut });

/**
 * Perguntas recebidas de uma sabatina real, preservadas na ordem da entrevista.
 * A resposta curta abre a conversa; os demais campos mostram como sustentá-la.
 */
export const realSabatinaQuestions: RealSabatinaQuestion[] = [
  q("sr-01", 8, "Fundamentos", "O que é um modelo?", "manter",
    "Um modelo é uma representação simplificada de um fenômeno, construída para estimar, classificar, explicar ou apoiar uma decisão a partir de dados.",
    "Em ciência de dados, ele aprende uma relação entre entradas e uma saída ou uma estrutura dos próprios dados. Não é a realidade: contém hipóteses, erros e um domínio de validade. Por isso, deve ser comparado com um baseline e avaliado em dados que não participaram do ajuste.",
    "Um modelo de risco pode transformar renda, histórico e comportamento em probabilidade de inadimplência. A decisão final ainda depende de política, custo, capacidade de pagamento e regras regulatórias.",
    "Não responda apenas “é um algoritmo”. Algoritmo é o procedimento de ajuste; modelo é a representação ajustada, com parâmetros, premissas e uso definido."),
  q("sr-02", 8, "Fundamentos", "O que é um modelo supervisionado e um não supervisionado?", "manter",
    "No supervisionado existe uma variável-alvo conhecida durante o treino; no não supervisionado procuramos estrutura sem um rótulo de resposta previamente informado.",
    "Classificação e regressão comparam previsões com o alvo para minimizar uma perda. Agrupamento, redução de dimensionalidade e detecção exploratória de anomalias buscam padrões de similaridade, densidade ou representação. “Não supervisionado” não significa “sem avaliação”: estabilidade e utilidade precisam ser verificadas.",
    "Supervisionado: prever atraso em 90 dias. Não supervisionado: segmentar clientes por comportamento para desenhar estratégias, sem declarar antecipadamente quais segmentos existem.",
    "Explique de onde vem o rótulo, quando ele fica disponível e se pode causar leakage."),
  q("sr-03", 8, "Fundamentos", "Pode dar exemplos das categorias de aprendizado?", "manter",
    "Classificação prevê classes; regressão prevê valores; clustering encontra grupos; redução de dimensionalidade cria representações compactas; aprendizado por reforço escolhe ações a partir de recompensas.",
    "A categoria depende da pergunta e da informação disponível. “Fraude ou não” é classificação; “qual será a perda” é regressão; “quais perfis de uso existem” é agrupamento. O mesmo conjunto de dados pode sustentar problemas diferentes.",
    "Crédito: classificação de default, regressão de perda esperada e clustering de perfis de utilização. A decisão de negócio vem antes da escolha do algoritmo.",
    "Não confunda agrupamento com classificação só porque ambos produzem números de grupo."),

  q("sr-04", 9, "Regressão", "Qual é a diferença entre regressão e classificação?", "manter",
    "Regressão estima uma quantidade numérica; classificação estima uma classe ou a probabilidade de uma classe.",
    "A diferença está na natureza do alvo e da perda. Regressão costuma otimizar erros como MSE ou MAE; classificação usa log loss, margem ou impureza e é avaliada por discriminação, calibração e custo do ponto de corte. Regressão logística, apesar do nome, é um classificador probabilístico.",
    "Prever valor de perda é regressão; estimar probabilidade de inadimplência é classificação. Se a decisão é aprovar ou negar, a probabilidade ainda precisa de threshold e política.",
    "Não defina classificação como “prever texto”: classes podem ser 0/1 e regressão pode prever qualquer valor contínuo."),
  q("sr-05", 9, "Regressão linear", "Como funciona a regressão linear?", "manter",
    "Ela ajusta coeficientes para que uma combinação linear das variáveis explique o alvo, normalmente minimizando a soma dos quadrados dos resíduos.",
    "No modelo y = β₀ + β₁x₁ + … + βpxp + ε, cada β mede a variação esperada em y para uma unidade de x, mantendo as demais constantes. O ajuste por mínimos quadrados busca o menor erro quadrático. A interpretação causal só é válida com desenho e hipóteses adicionais.",
    "Pode estimar gasto mensal ou tempo de atendimento quando a relação é aproximadamente aditiva. Coeficientes transparentes ajudam a discutir direção, magnitude e sensibilidade com risco e negócio.",
    "Sempre complemente com análise de resíduos, validação fora da amostra e verificação de multicolinearidade."),
  q("sr-06", 9, "Regressão linear", "Cite e explique uma premissa da regressão linear.", "manter",
    "Uma premissa central é a linearidade condicional: o valor esperado do alvo é uma combinação linear dos preditores nos parâmetros.",
    "Também se examinam independência dos erros, variância aproximadamente constante, ausência de multicolinearidade perfeita e exogeneidade E[ε|X]=0. Normalidade dos resíduos é especialmente relevante para inferência em amostras pequenas, não para o modelo produzir qualquer previsão.",
    "Em perda financeira, um funil de resíduos que cresce com o valor do contrato sugere heterocedasticidade; podemos transformar o alvo, usar erros robustos ou outro modelo.",
    "Evite listar premissas sem dizer como diagnosticá-las e o que faria se falhassem."),
  q("sr-07", 8, "Viés e variância", "Dê um exemplo de situação em que a regressão overfita e outra em que underfita.", "urgente",
    "Overfit: erro de treino muito baixo e erro de validação alto. Underfit: ambos os erros são altos porque a hipótese é simples ou mal especificada.",
    "Um polinômio de grau 15 com poucos dados pode memorizar ruído e overfitar; uma reta aplicada a uma relação fortemente curva pode underfitar. O diagnóstico exige a mesma métrica, split correto e comparação com baseline. Regularização, mais dados ou menor complexidade combatem overfit; melhores variáveis ou maior capacidade combatem underfit.",
    "Um modelo de perda que incorpora centenas de indicadores raros pode parecer perfeito no desenvolvimento e falhar no mês seguinte. Uma reta única para clientes de perfis muito distintos pode errar sistematicamente nos extremos.",
    "“Treino bom” sozinho não prova overfit: só a lacuna treino-validação, sem leakage, sustenta o diagnóstico."),
  q("sr-08", 10, "Regularização", "Na regressão existem penalidades. Qual é a diferença entre elas?", "manter",
    "L1 soma valores absolutos dos coeficientes e pode zerá-los; L2 soma seus quadrados e os encolhe de forma suave; Elastic Net combina as duas.",
    "L1 cria uma solução esparsa e pode selecionar uma variável entre correlacionadas. L2 distribui peso entre elas e costuma ser mais estável. A intensidade é controlada por alpha/lambda e deve ser escolhida dentro da validação; as variáveis numéricas precisam estar em escala comparável.",
    "Em score de crédito, L1 favorece uma ficha compacta; L2 pode estabilizar variáveis de comportamento correlacionadas. A escolha inclui estabilidade temporal e governança, não apenas AUC/RMSE.",
    "Não diga que L2 faz seleção automática: coeficientes podem ficar pequenos, mas em geral não chegam exatamente a zero."),
  q("sr-09", 10, "Pré-processamento", "Existe pré-processamento a ser feito antes de uma regressão?", "manter",
    "Sim. É preciso tratar tipos, faltantes, categorias, escala quando o método é sensível, outliers, distribuição e separar treino/teste antes de aprender qualquer transformação.",
    "O pipeline depende do estimador. Regressão linear pede diagnóstico de relação e resíduos; Ridge/Lasso exigem padronização para uma penalização comparável; categorias precisam de codificação sem ordem artificial. Imputadores, encoders e scalers devem ser ajustados só no treino.",
    "No banco, a data de referência é parte do pré-processamento: renda atualizada depois da decisão não pode entrar no treino. Também se verificam população, estabilidade e regras de negócio.",
    "Não aplique tratamento global antes do split; isso contamina a validação."),
  q("sr-10", 9, "Regressão linear", "Dê um exemplo em que regressão linear se encaixa bem e outro em que é ruim.", "urgente",
    "Ela se encaixa quando o alvo varia de modo aproximadamente linear e aditivo, com resíduos bem comportados; é ruim quando há não linearidades fortes, interações complexas ou resposta limitada que o modelo pode violar.",
    "Por exemplo, custo operacional pode crescer quase linearmente com volume dentro de uma faixa estável. Já preço com saltos por localização e interações pode exigir árvores ou transformação. A decisão deve vir de gráficos, resíduos e validação, não da aparência do nome da variável.",
    "Uma relação linear entre número de contatos e custo de cobrança pode ser útil para orçamento. Para probabilidade de default, regressão linear pode prever abaixo de 0 ou acima de 1; logística é mais adequada.",
    "Mesmo quando a previsão é boa, coeficientes não devem ser vendidos como efeitos causais."),
  q("sr-11", 9, "Multicolinearidade", "Por que é necessário retirar ou tratar colunas muito semelhantes entre si?", "urgente",
    "Porque preditores fortemente correlacionados tornam difícil separar seus efeitos, podendo deixar coeficientes instáveis e inflar a incerteza.",
    "A predição pode continuar razoável, mas pequenas mudanças nos dados alteram sinais e magnitudes. Podemos remover redundâncias, combinar variáveis, usar PCA ou regularização. A decisão depende do objetivo: inferência exige maior cuidado; predição prioriza estabilidade fora da amostra.",
    "Renda declarada e renda estimada podem competir no score. Manter ambas sem diagnóstico pode produzir explicações instáveis entre safras, o que prejudica governança.",
    "Correlação alta não obriga exclusão automática. Verifique VIF, estabilidade, semântica e valor incremental."),

  q("sr-12", 12, "Naive Bayes", "Qual é a principal premissa do Naive Bayes?", "manter",
    "As variáveis são assumidas condicionalmente independentes entre si dado o valor da classe.",
    "O modelo usa Bayes para combinar o prior da classe com as verossimilhanças de cada atributo. A hipótese é forte e raramente exata, mas o classificador pode funcionar bem porque precisa ordenar probabilidades de forma útil, especialmente em espaços esparsos.",
    "Em triagem de textos de atendimento, tokens ajudam a classificar motivo do contato. Mesmo palavras correlacionadas, o baseline costuma ser rápido e competitivo.",
    "Não diga que as variáveis são independentes no geral; a independência é condicionada à classe."),
  q("sr-13", 12, "Naive Bayes", "Como funciona o Naive Bayes?", "manter",
    "Ele calcula a probabilidade posterior de cada classe e escolhe a maior, combinando prior e verossimilhanças dos atributos.",
    "P(y|x) é proporcional a P(y) vezes o produto de P(xj|y). Na prática somamos log-probabilidades para evitar underflow. Cada variante define uma distribuição para os atributos. Suavização evita probabilidade zero para eventos não vistos.",
    "Um classificador de reclamações estima o prior de cada categoria e o quanto cada palavra é típica dela, encaminhando casos com baixa confiança para revisão.",
    "Probabilidades do Naive Bayes podem ser mal calibradas; avalie ranking e calibração separadamente."),
  q("sr-14", 12, "Naive Bayes", "Qual é um bom exemplo de problema para Naive Bayes?", "urgente",
    "Classificação de texto com muitas variáveis esparsas é um caso clássico: spam, assunto de e-mail, motivo de contato ou sentimento simples.",
    "Contagens ou presenças de palavras combinam naturalmente com Multinomial ou Bernoulli NB. O treino é rápido, funciona com poucos dados e estabelece um baseline interpretável. Ele perde força quando interações e ordem entre termos são decisivas.",
    "No banco, pode classificar mensagens em cartão, financiamento, fraude ou reclamação e priorizar filas, sempre medindo custo de roteamento errado.",
    "Não escolha Gaussian NB para contagens de palavras apenas por ser a variante mais conhecida."),
  q("sr-15", 12, "Naive Bayes", "Explique Multinomial, Bernoulli e Gaussian Naive Bayes.", "urgente",
    "Multinomial modela contagens/frequências não negativas; Bernoulli modela presença ou ausência; Gaussian assume atributo contínuo aproximadamente normal dentro de cada classe.",
    "Multinomial é comum com bag-of-words e TF-IDF não negativo; Bernoulli valoriza se o termo apareceu, não quantas vezes; Gaussian estima média e variância de cada variável por classe. A hipótese e a representação precisam combinar.",
    "Para e-mails bancários: Multinomial usa frequência de termos, Bernoulli usa indicadores de ocorrência e Gaussian poderia usar medidas contínuas como duração e valor, após validar sua adequação.",
    "Não compare variantes só pela acurácia: use validação estratificada, métrica de custo e calibração se a probabilidade apoiar decisão."),

  q("sr-16", 14, "Árvore de decisão", "Como é a estrutura de uma árvore de decisão?", "manter",
    "Ela tem um nó raiz, nós internos com regras de divisão, ramos que representam resultados dessas regras e folhas com a previsão final.",
    "Cada caminho equivale a uma sequência de condições. Em classificação, a folha guarda distribuição/proporção das classes; em regressão, geralmente uma média. Profundidade, número mínimo de amostras e poda controlam complexidade.",
    "Uma árvore de cobrança pode separar por atraso, exposição e histórico, produzindo grupos com probabilidades distintas e regras fáceis de explicar.",
    "A regra é aprendida dos dados; uma árvore profunda não é automaticamente uma política segura ou causal."),
  q("sr-17", 14, "Árvore de decisão", "Como é realizado o corte em uma árvore de decisão?", "manter",
    "O algoritmo testa variável e ponto de corte e escolhe a divisão que mais reduz a impureza ou o erro ponderado dos nós filhos.",
    "Para classificação são comuns Gini e entropia; para regressão, redução do MSE/variância ou MAE. Variáveis contínuas geram limiares e categorias podem ser codificadas conforme a implementação. O processo se repete até um critério de parada.",
    "Em risco, um corte como utilização > 85% só é aceito se melhorar o critério no treino e se mantiver estável em validação temporal e segmentos.",
    "Ganho local de impureza não garante melhor resultado de negócio nem generalização."),
  q("sr-18", 14, "Árvore de decisão", "Como a árvore chega à resposta final?", "manter",
    "A observação percorre as regras da raiz até uma folha; a folha devolve a classe, probabilidade ou valor agregado das amostras de treino que chegaram ali.",
    "Na classificação, predict_proba costuma ser a fração de classes na folha, sujeita a suavização/calibração. Na regressão, é comum usar a média do alvo. O threshold que converte probabilidade em ação é uma decisão posterior.",
    "Um cliente pode percorrer atraso > 30, exposição > limite e histórico curto, chegando a uma folha de alto risco; a política define a ação.",
    "Não confunda a folha com certeza individual: ela resume um grupo de treinamento."),
  q("sr-19", 14, "Pré-processamento de árvores", "Existe um tratamento de dados que não é obrigatório para árvores. Qual?", "manter",
    "Padronização ou normalização de escala normalmente não é necessária para árvores, porque os cortes dependem de ordenação e limiares, não de distância.",
    "Multiplicar uma variável por uma constante muda o valor do limiar, mas não a ordem das observações. Ainda é preciso tratar tipos, missings conforme a biblioteca, categorias, leakage e qualidade. Outliers podem afetar cortes, embora árvores sejam menos sensíveis que métodos lineares.",
    "Valor em reais e idade podem entrar em escalas diferentes numa árvore de risco sem StandardScaler. O pipeline, porém, ainda deve validar dados e codificar categorias corretamente.",
    "“Não precisa escalar” não significa “não precisa pré-processar”."),
  q("sr-20", 5, "Codificação de categorias", "Qual a diferença entre OneHotEncoder e LabelEncoder e quando usar cada um?", "manter",
    "One-hot cria uma coluna indicadora por categoria; LabelEncoder transforma cada rótulo em um inteiro e é destinado principalmente ao alvo.",
    "One-hot evita criar uma ordem artificial e é seguro para categorias nominais, respeitando categorias desconhecidas. LabelEncoder em atributos pode fazer o modelo interpretar 2 como maior que 1. Para variáveis realmente ordinais, use OrdinalEncoder com ordem explícita.",
    "Estado civil ou canal de aquisição pedem one-hot; uma classe alvo “bom/ruim” pode ser codificada 0/1. Faixa de risco baixa/média/alta pode usar ordem explícita.",
    "Diferencie LabelEncoder de OrdinalEncoder e ajuste o encoder somente no treino."),
  q("sr-21", 6, "Pipeline", "Qual sequência você usaria para dividir treino/teste e fazer transformações?", "urgente",
    "Defino unidade, alvo e tempo; separo treino, validação e teste; ajusto imputação, encoding e escala apenas no treino; treino e ajusto hiperparâmetros na validação/CV; avalio uma vez no teste intocado.",
    "Em dados temporais, os períodos futuros ficam à frente. O Pipeline/ColumnTransformer impede etapas soltas. Reamostragem de classe acontece só nos folds de treino. Após escolher tudo, pode-se reajustar com treino+validação e manter teste/OOT como auditoria final.",
    "Para crédito, variáveis precisam existir na data da proposta; o teste pode ser uma safra futura e a avaliação deve incluir discriminação, calibração e negócio.",
    "O erro mais grave é calcular média, escala, seleção ou oversampling antes do split."),
  q("sr-22", 8, "Busca de hiperparâmetros", "Cite duas técnicas para buscar hiperparâmetros.", "reforcar",
    "Grid Search e Randomized Search são duas técnicas; otimização bayesiana é uma terceira alternativa.",
    "Grid testa todas as combinações de uma grade finita; Randomized sorteia um orçamento de combinações a partir de distribuições. Em ambos, a qualidade é medida por um scoring coerente dentro de validação cruzada. A técnica de busca não é a métrica.",
    "Em fraude, podemos otimizar PR-AUC ou recall sob limite de falsos positivos, não acurácia, e usar split temporal nos folds.",
    "Se a pergunta disser “métricas”, esclareça a ambiguidade: cite as estratégias e depois a métrica de scoring."),
  q("sr-23", 8, "Busca de hiperparâmetros", "Qual a diferença entre Grid Search e Randomized Search?", "manter",
    "Grid avalia a grade inteira; Randomized avalia uma amostra de combinações dentro de um orçamento.",
    "Grid é previsível e útil em espaços pequenos. Randomized explora melhor espaços grandes e contínuos com o mesmo custo, especialmente quando poucos parâmetros importam. Ambos precisam de CV correta e um espaço de busca plausível; busca bayesiana usa resultados anteriores para escolher a próxima tentativa.",
    "Para boosting com learning_rate, profundidade e número de árvores, busca aleatória costuma encontrar regiões melhores sem explodir o custo.",
    "Não use o conjunto de teste a cada tentativa; isso transforma teste em validação e otimiza por vazamento."),
  q("sr-24", 14, "Classes desbalanceadas", "Quais técnicas ajudam quando as classes estão desequilibradas?", "reforcar",
    "Podemos ajustar pesos/custos, fazer oversampling ou undersampling no treino, criar dados sintéticos com cuidado, ajustar threshold e escolher métricas apropriadas.",
    "A primeira etapa é entender prevalência e custo. class_weight preserva dados; oversampling replica ou sintetiza a minoria; undersampling reduz a maioria; ensembles balanceados combinam amostras. Tudo deve ocorrer dentro do fold de treino. A calibração precisa considerar a prevalência real.",
    "Em fraude rara, PR-AUC, recall em uma capacidade fixa e precisão da fila são mais informativos. O threshold pode ser escolhido pelo número de casos que a equipe consegue investigar.",
    "Desbalanceamento não é resolvido apenas “deixando 50/50”; isso pode distorcer probabilidade e operação."),
  q("sr-25", 14, "Classes desbalanceadas", "Como funcionam oversampling e undersampling?", "manter",
    "Oversampling aumenta a representação da minoria; undersampling reduz a maioria no conjunto de treino.",
    "Oversampling aleatório replica exemplos e pode overfitar; SMOTE interpola vizinhos e pode gerar pontos pouco plausíveis. Undersampling acelera o treino, mas descarta informação. A validação e o teste mantêm a distribuição original para medir o cenário real.",
    "Para fraude, podemos fazer undersampling da maioria para experimentar rápido e pesos/oversampling para o modelo final, sempre medindo precisão da fila e recall.",
    "Nunca reamostre antes do split nem avalie numa base artificialmente balanceada."),
  q("sr-26", 14, "Classes desbalanceadas", "Quando é melhor usar oversampling ou undersampling?", "urgente",
    "Oversampling é preferível quando a minoria é pequena e não queremos perder maioria; undersampling é útil quando a maioria é enorme, redundante e o custo computacional pesa.",
    "A escolha depende de volume, diversidade e algoritmo. Com poucos positivos, replicar demais pode memorizar; com milhões de negativos semelhantes, descartar uma parte pode ser eficiente. Pesos de classe frequentemente são um bom baseline. Compare por validação estratificada ou temporal e custo operacional.",
    "Em antifraude com milhões de transações legítimas, undersampling controlado acelera protótipos; para eventos raríssimos e heterogêneos, preservamos positivos e usamos pesos, investigação e coleta de novos rótulos.",
    "SMOTE não entende automaticamente regras de negócio, tempo ou variáveis categóricas."),
  q("sr-27", 14, "Árvore de decisão", "Dê uma vantagem e uma desvantagem da árvore de decisão.", "manter",
    "Vantagem: captura não linearidades e interações com pouca preparação e é explicável quando pequena. Desvantagem: uma árvore isolada é instável e tende a overfitar.",
    "Pequenas mudanças na amostra podem alterar cortes e estrutura. Profundidade, folhas mínimas e poda ajudam, enquanto ensembles reduzem variância. A interpretabilidade cai rapidamente quando a árvore cresce.",
    "Uma árvore rasa pode produzir regras de priorização de cobrança auditáveis; para máximo desempenho, Random Forest ou boosting podem ser melhores, com explicação adicional.",
    "Não chame toda árvore de interpretável: uma árvore com centenas de nós não é operacionalmente simples."),

  q("sr-28", 16, "Ensembles", "Quais são os principais tipos de ensemble?", "urgente",
    "Bagging, boosting e stacking/voting são as famílias mais comuns.",
    "Bagging treina modelos em paralelo em amostras e agrega previsões; boosting treina sequencialmente para corrigir erros; stacking usa previsões de modelos-base como entrada de um meta-modelo; voting faz combinação direta. Random Forest é bagging com descorrelação de atributos; Gradient Boosting é boosting.",
    "Em risco, podemos comparar Random Forest, XGBoost e um stacking com logística, mas o ganho deve compensar custo, latência e governança.",
    "“Random Forest e XGBoost” são exemplos, não os tipos conceituais."),
  q("sr-29", 16, "Ensembles", "Explique as diferenças entre os ensembles e dê exemplos.", "manter",
    "Bagging reduz instabilidade pela média; boosting constrói uma soma sequencial de correções; stacking aprende como combinar modelos diferentes.",
    "No bagging, learners podem ser treinados em paralelo e cada um vê uma amostra bootstrap. No boosting, cada etapa enfatiza resíduos ou exemplos difíceis. No stacking, previsões out-of-fold evitam leakage no meta-modelo. Exemplos: Random Forest, AdaBoost/Gradient Boosting e logística combinando árvores e redes.",
    "Um banco pode usar Random Forest como baseline robusto, boosting para ranking e stacking apenas se o ganho OOT justificar complexidade operacional.",
    "Stacking treinado com previsões in-sample causa leakage e desempenho ilusório."),
  q("sr-30", 16, "Bootstrap", "Como funciona o bootstrap?", "manter",
    "Ele cria novas amostras sorteando observações com reposição a partir da amostra original, geralmente mantendo o mesmo tamanho.",
    "Como há reposição, algumas linhas se repetem e outras ficam de fora; estas formam o conjunto out-of-bag. Repetições permitem estimar variabilidade de estatísticas e treinar modelos diversos no bagging. Independência da unidade amostral precisa ser respeitada.",
    "Em dados de clientes, o sorteio deve ocorrer por cliente, não por transação, se várias linhas pertencem à mesma pessoa. Em tempo, bootstrap ingênuo pode quebrar dependência.",
    "Não confunda bootstrap com divisão sem reposição ou com validação temporal."),
  q("sr-31", 16, "Viés e variância", "Entre bagging e boosting, qual reduz variância e qual reduz viés?", "manter",
    "Em termos gerais, bagging reduz variância; boosting tende a reduzir viés ao adicionar correções sequenciais.",
    "A média de modelos instáveis descorrelacionados cancela parte do ruído, como na Random Forest. Boosting soma learners fracos para representar relações mais complexas. Na prática, boosting também pode reduzir variância com regularização e bagging não elimina viés; é uma orientação, não uma lei absoluta.",
    "Se uma árvore isolada oscila muito entre safras, bagging estabiliza. Se um baseline simples erra padrões sistemáticos, boosting pode capturá-los.",
    "Mostre a nuance: profundidade, learning rate, amostragem e dados alteram o balanço."),
  q("sr-32", 7, "Métricas de classificação", "Cite quatro métricas de classificação.", "manter",
    "Precision, recall, F1 e AUC ROC. Também são comuns PR-AUC, KS, Gini, log loss e acurácia.",
    "Cada métrica responde a uma pergunta. Precision mede qualidade dos positivos acionados; recall mede cobertura dos positivos reais; F1 harmoniza os dois; AUC mede ranking entre classes ao longo de thresholds. Log loss avalia a qualidade probabilística e calibração é analisada à parte.",
    "Fraude pode usar recall com capacidade fixa e precision da fila; crédito usa Gini/KS para discriminação e métricas de calibração para probabilidade.",
    "Citar métricas sem definir positivo, custo e população deixa a resposta incompleta."),
  q("sr-33", 7, "Acurácia", "Qual é o objetivo da acurácia?", "manter",
    "Medir a proporção total de previsões corretas entre todas as observações.",
    "É (VP + VN)/N. Funciona quando classes e custos são razoavelmente equilibrados, mas pode esconder falha completa na classe rara. Também depende do threshold escolhido.",
    "Se 99,5% das transações são legítimas, prever tudo como legítimo dá 99,5% de acurácia e detecta zero fraude.",
    "Acurácia não é sempre ruim; ela é inadequada quando prevalência ou custo tornam os erros muito diferentes."),
  q("sr-34", 7, "Recall", "O que o recall mede?", "manter",
    "A fração dos positivos reais que o modelo conseguiu identificar: VP/(VP+FN).",
    "Ele responde “de tudo que realmente era positivo, quanto encontrei?”. Aumentar recall geralmente reduz precision ao baixar o threshold. A classe positiva precisa ser definida explicitamente.",
    "Em fraude, recall mede a parcela das fraudes capturadas; em cobrança, pode medir quantos clientes que entrariam em atraso foram alcançados.",
    "Não diga que recall mede acertos totais nem ignore o custo de falsos positivos."),
  q("sr-35", 7, "Precision", "O que a precisão mede?", "manter",
    "A fração das previsões positivas que realmente eram positivas: VP/(VP+FP).",
    "Ela responde “dos casos que acionei, quantos estavam corretos?”. É muito dependente da prevalência e do threshold. Alta precision pode coexistir com baixo recall.",
    "Na fila de investigação, precision indica quantos alertas são fraudes confirmadas e ajuda a medir desperdício de capacidade.",
    "Em português, diferencie precisão/precision de acurácia/accuracy."),
  q("sr-36", 7, "Gini", "O que o Gini mede e o que ele nos diz?", "urgente",
    "O Gini de modelo mede poder de discriminação/ranking e, na convenção usual, é 2×AUC−1.",
    "Ele indica quanto o ranking separa positivos de negativos em relação ao acaso. Gini 1 é separação perfeita, 0 equivale a AUC 0,5 e ranking aleatório, e valor negativo sugere ordenação invertida. Não mede calibração nem ganho financeiro diretamente.",
    "Em crédito, Gini 0,55 indica boa ordenação relativa de risco, mas ainda precisamos verificar calibração, estabilidade OOT, segmentos e política de corte.",
    "Não confunda Gini do modelo com impureza de Gini usada dentro de árvores."),
  q("sr-37", 7, "Gini", "Se um modelo tem Gini de 50%, ele funciona como uma moeda?", "urgente",
    "Não. Gini de 50% corresponde a AUC de 75%, portanto há discriminação relevante; moeda/aleatório corresponde a Gini 0% e AUC 50%.",
    "Pela relação Gini = 2×AUC−1, AUC = (0,50+1)/2 = 0,75. Isso significa que um positivo recebe score maior que um negativo em cerca de 75% dos pares aleatórios, sob a definição da classe e sentido do score.",
    "Um score de crédito com Gini 50% pode ordenar risco de forma útil, mas a aprovação depende também de calibração, custo e estabilidade.",
    "Sempre confirme se a organização reporta Gini em 0–1 ou 0–100 e qual classe/sentido do score."),
  q("sr-38", 7, "Métricas de classificação", "Por que muitas áreas não usam acurácia e qual métrica seria melhor?", "reforcar",
    "Porque classes e custos costumam ser desequilibrados; a melhor métrica depende da decisão, podendo ser recall, precision, PR-AUC, AUC/Gini, F1 ou custo esperado.",
    "Não existe substituta universal. Para ranking, AUC/Gini; para evento raro e fila, PR-AUC/precision/recall; para probabilidade, log loss, Brier e calibração; para política, lucro ou perda esperada no threshold.",
    "Em fraude, uma métrica adequada pode ser recall dentro dos 2 mil alertas que a operação consegue revisar, acompanhado da precision dessa fila.",
    "Responder apenas “F1” sem explicar o custo de falso positivo e falso negativo é insuficiente."),
  q("sr-39", 7, "Curva ROC", "Como é feita a curva ROC e o que ela nos diz?", "manter",
    "Variamos o threshold do score e plotamos taxa de verdadeiros positivos contra taxa de falsos positivos.",
    "Cada threshold gera TPR=recall e FPR=FP/(FP+TN). A curva mostra o compromisso entre capturar positivos e alarmar negativos; a AUC resume a capacidade de ranking. O ponto de operação deve considerar custo e capacidade, não apenas a distância ao canto superior esquerdo.",
    "Em crédito, a ROC compara discriminação entre scores, enquanto o threshold final pode ser escolhido por perda esperada, apetite de risco e volume de aprovação.",
    "Em eventos muito raros, complemente com Precision-Recall porque um FPR pequeno ainda pode gerar muitos falsos positivos."),
  q("sr-40", 6, "Validação", "Por que separar treino e teste? Dê um exemplo.", "manter",
    "Para estimar como o modelo generaliza em dados não vistos e detectar memorização ou escolhas que só funcionaram no desenvolvimento.",
    "O treino ajusta parâmetros; validação escolhe pipeline e hiperparâmetros; teste fica intocado para avaliação final. Se o problema tem tempo, o futuro deve estar no teste. Transformações são aprendidas só no treino.",
    "Treinamos risco com propostas de janeiro a setembro, validamos em outubro e testamos em novembro/dezembro, respeitando quando o default amadurece.",
    "Um split aleatório pode vazar o futuro ou o mesmo cliente entre conjuntos."),
  q("sr-41", 6, "Validação", "Explique holdout e k-fold.", "manter",
    "Holdout usa uma divisão fixa; k-fold divide os dados em k partes e alterna cada parte como validação.",
    "Holdout é simples e barato, mas sua estimativa depende mais de uma única divisão. K-fold produz k resultados e usa média/dispersão, com maior custo. StratifiedKFold preserva proporções de classe; GroupKFold mantém grupos; séries temporais exigem splits progressivos.",
    "Em base de clientes independentes, k-fold estratificado pode ser adequado. Em safras de crédito, validação temporal/OOT é mais fiel à produção.",
    "K-fold aleatório não é automaticamente melhor se viola tempo ou grupos."),
  q("sr-42", 6, "Validação cruzada", "Como funciona uma validação cruzada?", "manter",
    "O pipeline é treinado em subconjuntos e validado na parte deixada de fora repetidamente; no fim agregamos as métricas.",
    "Em k-fold, cada observação participa da validação uma vez e do treino k−1 vezes. Todo pré-processamento e reamostragem devem ser reajustados dentro de cada fold. Reporte média, dispersão e, quando relevante, desempenho por período/segmento.",
    "Para escolher profundidade de árvore, cada candidata é comparada nos mesmos folds; o teste final só é aberto após a escolha.",
    "Fazer o scaler na base inteira antes da CV é leakage, mesmo que o algoritmo seja refeito em cada fold."),
  q("sr-43", 6, "Validação cruzada", "Por que usamos validação cruzada?", "manter",
    "Para obter uma estimativa menos dependente de uma única divisão e comparar alternativas com maior segurança.",
    "Ela ajuda a estimar variabilidade, usar dados escassos com eficiência e escolher hiperparâmetros. Não elimina viés de seleção nem substitui teste final/OOT. Se repetimos muitas escolhas nos mesmos folds, ainda podemos overfitar à validação.",
    "Em uma carteira pequena, folds por cliente dão uma faixa mais confiável para a métrica; uma safra futura confirma estabilidade temporal.",
    "Não diga que CV “cria mais dados”; ela reutiliza observações para avaliação controlada."),
  q("sr-44", 16, "Monitoramento", "O Gini era 55% no desenvolvimento e caiu para 45% em produção. Como validar o modelo?", "manter",
    "Primeiro confirmo que cálculo, janela, alvo e população são comparáveis; depois investigo qualidade dos dados, drift, estabilidade por segmento, atraso de rótulo e mudança de processo.",
    "Reproduzo a métrica com pipeline versionado, intervalos de confiança e mesma definição. Comparo score e variáveis entre treino/OOT/produção, PSI/CSI, missing, categorias novas, volume e taxa de evento. Analiso Gini por safra e segmento, calibração e resultado de negócio. Só então decido corrigir dados, recalibrar, reajustar ou substituir.",
    "Uma mudança de política de aprovação altera a população observada; comparar Gini bruto sem controlar essa seleção pode produzir conclusão errada.",
    "Não retreine imediatamente: primeiro descarte bug, mudança de rótulo, maturação incompleta e population shift."),
  q("sr-45", 16, "Monitoramento", "O que validar nas bases de um modelo e quais métricas usar?", "urgente",
    "Valido schema, volume, unicidade, cobertura, missing, faixa, categorias, distribuição, tempo, target e relação entre score e resultado.",
    "Uso contagens e taxas de erro para qualidade; PSI/CSI, KS entre distribuições, distância ou divergência para drift; taxa de evento e maturação do alvo; Gini/AUC/KS para discriminação; Brier, log loss e curva de calibração; métricas por segmento e estabilidade temporal. Limites devem gerar ação e responsável.",
    "No banco, monitoro atraso de carga, duplicidade de cliente-mês, renda faltante, categoria nova, mudança da população aprovada, bad rate, Gini e perda financeira.",
    "PSI não é prova causal de degradação e não existe um corte universal válido para toda variável."),

  q("sr-46", 17, "K-means", "Como funciona o k-means?", "manter",
    "Ele alterna a atribuição de cada ponto ao centroide mais próximo e a atualização de cada centroide pela média dos pontos atribuídos.",
    "O objetivo é minimizar a soma das distâncias quadráticas dentro dos clusters. É preciso escolher K, escala e inicialização; k-means++ e múltiplas seeds reduzem soluções locais ruins. Funciona melhor com grupos aproximadamente compactos e de variância semelhante.",
    "Pode segmentar clientes por utilização, saldo e frequência para desenhar jornadas, desde que os perfis sejam estáveis e acionáveis.",
    "O número do cluster não tem ordem nem significado automático; ele precisa de perfil e nome de negócio."),
  q("sr-47", 17, "K-means", "Com outlier, o k-means continua funcionando normalmente?", "manter",
    "Ele executa, mas pode ser fortemente distorcido, porque centroides usam médias e o objetivo quadrático dá peso grande a pontos distantes.",
    "Um extremo pode puxar o centroide, aumentar a inércia e alterar fronteiras. Investigue o dado, aplique transformação/capping justificado, segmente populações ou compare k-medoids, que usa observações reais como centros e é mais robusto.",
    "Um cliente corporate misturado com varejo pode dominar escala de saldo. A solução talvez seja separar populações, não simplesmente apagar o caso.",
    "Outlier não é sinônimo de erro; pode representar um segmento valioso ou fraude."),
  q("sr-48", 17, "K-means", "Qual pré-processamento é necessário para k-means?", "manter",
    "Selecionar variáveis coerentes, tratar faltantes e outliers, codificar categorias adequadamente e padronizar escalas é normalmente essencial.",
    "Como o algoritmo usa distância, uma variável com unidade maior domina. StandardScaler ou método robusto é ajustado no treino/base de referência. Variáveis redundantes também pesam repetidamente a mesma dimensão; PCA pode ajudar, com custo de interpretação.",
    "Saldo em milhares e frequência em unidades precisam de escala comparável antes de segmentar clientes. Depois, descreva clusters nas unidades originais.",
    "One-hot de alta cardinalidade pode distorcer distância; escolha representação compatível com a pergunta."),
  q("sr-49", 17, "Validação de clustering", "Cite métricas para validar agrupamento.", "manter",
    "Silhouette, inércia/WCSS, Davies–Bouldin e Calinski–Harabasz são internas; ARI, NMI e Rand são externas quando existe referência.",
    "Métricas internas usam coesão e separação, mas favorecem geometrias diferentes. Também avalie estabilidade em reamostragens, tamanho dos grupos, interpretabilidade e capacidade de acionar estratégia. Clustering não tem uma única “acurácia”.",
    "Segmentos bancários devem manter perfil entre safras e produzir ações distintas; silhouette alta sem valor operacional não basta.",
    "Compare métricas na mesma representação e escala; valores entre datasets diferentes não são diretamente comparáveis."),
  q("sr-50", 17, "Escolha de K", "Entre curva do cotovelo e silhueta, qual você recomenda?", "manter",
    "Eu usaria ambas como evidência e tenderia à silhueta quando preciso comparar coesão e separação; a decisão final inclui estabilidade e utilidade de negócio.",
    "O cotovelo procura onde o ganho marginal de inércia diminui, mas pode ser subjetivo e a inércia sempre cai com K. Silhouette combina distância ao próprio grupo e ao vizinho mais próximo. Nenhuma corrige uma geometria inadequada ao k-means.",
    "Se K=4 maximiza silhouette, mas produz dois segmentos minúsculos impossíveis de operar, K=3 estável e acionável pode ser melhor.",
    "Não escolha K só porque o gráfico parece bonito; documente trade-off e sensibilidade a seeds."),
  q("sr-51", 17, "Silhueta", "O que o coeficiente de silhueta avalia?", "manter",
    "Ele compara a coesão de um ponto com seu próprio cluster e sua separação em relação ao cluster vizinho mais próximo.",
    "s=(b−a)/max(a,b), em que a é a distância média intracluster e b a menor distância média para outro cluster. Próximo de 1 indica boa atribuição, perto de 0 fronteira e negativo possível alocação inadequada. Analise média e distribuição por cluster.",
    "Num segmento de clientes, uma silhouette média razoável pode esconder um grupo mal definido; examine o valor por perfil antes de criar campanha.",
    "Silhouette pressupõe que a métrica de distância representa similaridade útil para o negócio."),
];

export const sabatinaPriorityLabel: Record<SabatinaPriority, string> = {
  manter: "Respondida bem · manter afiada",
  reforcar: "Resposta parcial · reforçar",
  urgente: "Não respondida · revisão urgente",
};

export function realSabatinaForWeek(week: number) {
  return realSabatinaQuestions.filter((item) => item.week === week);
}

export function fullSabatinaAnswer(item: RealSabatinaQuestion) {
  return `${item.answer} ${item.reasoning} Aplicação bancária: ${item.banking} Atenção: ${item.watchOut}`;
}
