export const officialBlocks = [
  {
    title: "PROGRAMAÇÃO",
    weekNumbers: [7],
    items: [
      ["Fluência na sintaxe básica", 7],
      ["Métodos e pacotes para leitura e escrita de dados", 7],
      ["Fluência nos principais pacotes de machine learning (Python: sklearn / R: caret, mlr)", 7],
    ],
  },
  {
    title: "ESTATÍSTICA BÁSICA",
    weekNumbers: [1, 2, 3],
    items: [
      ["Variáveis aleatórias contínuas e discretas", 1],
      ["Função densidade de probabilidade e distribuição acumulada", 2],
      ["Propriedades de distribuições (médias, medianas, quartis, moda, variância, etc.)", 1],
      ["Testes de hipóteses", 3],
      ["Principais distribuições: Normal, Bernoulli, Binomial, Uniforme, Poisson, Geométrica", 2],
    ],
  },
  {
    title: "ÁLGEBRA",
    weekNumbers: [4],
    items: [
      ["Matrizes e Vetores", 4],
      ["Álgebra Matricial", 4],
      ["Distâncias e produto interno", 4],
    ],
  },
  {
    title: "AVALIAÇÃO DE MODELOS",
    weekNumbers: [9],
    items: [
      ["Métricas de avaliação de modelo: KS, Gini, AUC, RMSE, MAE, F1, Recall, Precision, R2", 9],
      ["Validações holdout, leave one out, k-fold, out of sample, out of time", 9],
    ],
  },
  {
    title: "DATA PREP",
    weekNumbers: [5, 6],
    items: [
      ["Tratamento de missings", 5],
      ["Tratamento de outliers", 5],
      ["Categorização de variáveis contínuas e discretas", 5],
      ["PCA", 6],
      ["Correlação / associação entre dados contínuos e entre dados discretos", 6],
      ["Seleção de variáveis", 6],
    ],
  },
  {
    title: "BANCO DE DADOS",
    weekNumbers: [8],
    items: [
      ["Modelo de banco de dados relacional", 8],
      ["Sintaxe de SQL", 8],
      ["Álgebra relacional: join, group by, order by e etc.", 8],
      ["Chaves primárias, secundárias e estrangeiras", 8],
    ],
  },
  {
    title: "CLASSIFICAÇÃO",
    weekNumbers: [12, 13, 14, 15],
    items: [
      ["Árvore de classificação", 14],
      ["Random Forest", 14],
      ["Estratégias de Boosting (Gradient, ADA, etc.)", 14],
      ["Regressão Logística", 12],
      ["KNN", 13],
      ["Naive Bayes", 12],
      ["Redes Neurais", 15],
      ["SVM", 13],
    ],
  },
  {
    title: "REGRESSÃO",
    weekNumbers: [10, 11],
    items: [
      ["Regressão Linear", 10],
      ["Regularização L1 e L2", 11],
      ["Árvore de Regressão", 11],
      ["Análise de Resíduos", 10],
      ["Modelos lineares generalizados (GLM)", 11],
    ],
  },
  {
    title: "AGRUPAMENTO",
    weekNumbers: [16, 17],
    items: [
      ["K-means / K-medoids", 16],
      ["DBSCAN", 17],
      ["Algoritmos Hierárquicos", 17],
      ["Estratégias de definição do número de cluster", 16],
      ["Gaussian Mixture Models (GMM)", 17],
    ],
  },
  {
    title: "IA GENERATIVA",
    weekNumbers: [18, 19],
    items: [
      ["Conceitos fundamentais de IA Generativa e NLP", 18],
      ["Arquitetura transformer", 18],
      ["In Context Learning", 18],
      ["RAGs e bancos de dados vetoriais", 19],
      ["Engenharia de Prompt", 18],
      ["Técnicas de treinamento e fine tuning", 19],
      ["Quantization", 19],
      ["Embeddings", 19],
      ["RLHF", 19],
      ["Safeguards e Guardrails", 19],
    ],
  },
  {
    title: "PESQUISA OPERACIONAL",
    weekNumbers: [20],
    items: [
      ["Programação linear", 20],
      ["Modelos de programação linear", 20],
      ["Solução gráfica e simplex", 20],
    ],
  },
  {
    title: "PROGRAMAÇÃO INTEIRA",
    weekNumbers: [21],
    items: [
      ["Variáveis inteiras e binárias, otimização discreta", 21],
      ["Relaxação linear", 21],
      ["Arredondamento", 21],
      ["Método Branch-and-bound", 21],
    ],
  },
  {
    title: "MIP (MIXED INTEGER PROGRAM)",
    weekNumbers: [22],
    items: [
      ["O que é MIP", 22],
      ["GAP e Best Bound", 22],
      ["Solvers", 22],
    ],
  },
];

const resources = {
  statistics: {
    books: ["Livro 2 — capítulos 1 a 8 (probabilidade, distribuições e inferência)", "Douglas — capítulos 2 e 3 (Estatística e testes de hipótese)", "Luiza — páginas 1 a 11", "Livro 3 — capítulos 7 e 8 (pandas e visualização)"],
    videos: ["StatQuest — Statistics Fundamentals", "Khan Academy — Probability and Statistics", "3Blue1Brown — visualização de probabilidade"],
    articles: ["SciPy User Guide — Statistical functions", "NIST/SEMATECH e-Handbook of Statistical Methods", "Documentação statsmodels — Statistics"],
  },
  algebra: {
    books: ["Douglas — capítulo 1 (Álgebra)", "Livro 1 — capítulos 2 e 4", "Luiza — páginas 12 a 16", "Livro 3 — capítulo 7 (NumPy)"],
    videos: ["3Blue1Brown — Essence of Linear Algebra", "MIT OpenCourseWare — Linear Algebra", "StatQuest — distância e similaridade"],
    articles: ["NumPy — Linear algebra", "scikit-learn — Pairwise metrics", "Stanford CS229 — Linear Algebra Review"],
  },
  dataPrep: {
    books: ["Luiza — páginas 17 a 27", "Livro 1 — capítulo 3 (Pré-processamento)", "Douglas — capítulos 4 e 5", "Livro 2 — capítulo 5"],
    videos: ["StatQuest — PCA", "scikit-learn — preprocessing visual guides", "Data School — leakage e pipelines"],
    articles: ["scikit-learn — Common pitfalls and recommended practices", "scikit-learn — Imputation, preprocessing and feature selection", "Google ML — Data preparation and leakage"],
  },
  programming: {
    books: ["Livro 3 — capítulos 1 a 8", "Douglas — capítulo 15 como checklist", "Luiza — páginas 17 a 18 e 28 a 31", "Python Data Science Handbook"],
    videos: ["CS50P — Introduction to Programming with Python", "Corey Schafer — Python Tutorials", "scikit-learn MOOC"],
    articles: ["Python Tutorial oficial", "pandas — Getting Started", "scikit-learn — User Guide"],
  },
  database: {
    books: ["Hashtag Programação — curso de SQL", "Livro 3 — sqlite3 e pandas.read_sql", "Douglas — capítulo 15", "Ementa oficial como checklist literal"],
    videos: ["SQLBolt — Interactive SQL Lessons", "Khan Academy — Intro to SQL", "DuckDB — Getting Started"],
    articles: ["PostgreSQL Tutorial — SQL language", "DuckDB documentation", "dbt — SQL style and data tests"],
  },
  evaluation: {
    books: ["Livro 1 — capítulo 10", "Livro 3 — capítulos 9 a 16", "Douglas — capítulos 6 a 9", "Luiza — páginas 28 a 81"],
    videos: ["StatQuest — ROC and AUC", "Google ML Crash Course — Classification", "scikit-learn MOOC — model evaluation"],
    articles: ["scikit-learn — Model evaluation", "scikit-learn — Cross-validation", "Google ML — Classification metrics"],
  },
  regression: {
    books: ["Livro 2 — capítulo 9", "Livro 3 — capítulos 9 a 12 e 15", "Luiza — páginas 28 a 52 e 66 a 71", "Douglas — capítulos 8 e 9"],
    videos: ["StatQuest — Linear Models", "StatQuest — Ridge and Lasso", "ISLR lectures — Linear Regression"],
    articles: ["scikit-learn — Linear models", "statsmodels — Regression diagnostics", "Penn State STAT 501 — Regression methods"],
  },
  classification: {
    books: ["Livro 1 — capítulos 4 a 9", "Livro 3 — capítulos 12 a 16", "Douglas — capítulos 6, 7 e 14", "Luiza — páginas 53 a 81"],
    videos: ["StatQuest — Machine Learning playlist", "Google ML Crash Course — Classification", "scikit-learn MOOC — supervised learning"],
    articles: ["scikit-learn — Supervised learning", "Google ML — Classification", "Interpretable Machine Learning — model chapters"],
  },
  clustering: {
    books: ["Luiza — páginas 82 a 96", "Livro 1 — capítulos 12, 13 e 15", "Douglas — capítulos 10 e 11", "Livro 2 — Normal como apoio ao GMM"],
    videos: ["StatQuest — K-means", "StatQuest — Gaussian Mixture Models", "scikit-learn — clustering comparison"],
    articles: ["scikit-learn — Clustering", "scikit-learn — Gaussian mixture models", "Interpretable clustering guidance"],
  },
  genAi: {
    books: ["Livro 1 — capítulo 19 e seção 7.7", "Douglas — capítulo 12", "Luiza — páginas 97 a 109 como glossário", "Hugging Face Course"],
    videos: ["Hugging Face Course", "Andrej Karpathy — Let's build GPT", "DeepLearning.AI — Generative AI short courses"],
    articles: ["The Illustrated Transformer", "Hugging Face — NLP Course", "OWASP Top 10 for LLM Applications"],
  },
  optimization: {
    books: ["Douglas — capítulo 13 (Pesquisa Operacional)", "Google OR-Tools — guias de LP e MIP", "Ementa oficial como checklist literal", "Introdução à Pesquisa Operacional — Hillier e Lieberman"],
    videos: ["MIT OpenCourseWare — Optimization Methods", "Google OR-Tools tutorials", "Solução gráfica e Simplex — aulas introdutórias"],
    articles: ["Google OR-Tools — Linear Optimization", "Google OR-Tools — MIP", "HiGHS — documentation"],
  },
};

export const weekSpecs = [
  {
    number: 1, title: "Variáveis aleatórias e medidas descritivas", period: "03–09 ago", block: "ESTATÍSTICA BÁSICA", resources: resources.statistics,
    summary: "Construa a linguagem probabilística usada para representar incerteza e resumir carteiras bancárias sem esconder assimetria, dispersão ou caudas.",
    content: ["Variável aleatória, espaço amostral, suporte e evento", "Diferença entre variável contínua e discreta", "Média, mediana, moda, quartis e percentis", "Esperança, variância, desvio-padrão e coeficiente de variação", "Assimetria, caudas, boxplot e leitura crítica de agregações"],
    foundation: "Uma variável aleatória é uma função que associa resultados de um experimento a números. Nas discretas há probabilidades pontuais; nas contínuas, probabilidades vêm de áreas sob uma densidade. Medidas de posição descrevem centro e quantis, enquanto variância e desvio-padrão descrevem dispersão. Nenhuma medida isolada representa bem todas as distribuições.",
    mechanism: "O trabalho começa definindo população, unidade de análise e variável. Depois se examinam suporte, frequência, quantis, assimetria e dispersão. Média é sensível a extremos; mediana é robusta; quartis revelam concentração. A escolha do resumo deve seguir a pergunta de decisão, e não a conveniência do cálculo.",
    formula: "E[X]=\\sum_x x p(x)\\;\\text{ou}\\;\\int x f(x)dx,\\qquad Var(X)=E[(X-E[X])^2]",
    mathExplanation: "Esperança é a média teórica ponderada pela probabilidade; variância é a distância quadrática média até a esperança. Em amostra, use denominador n−1 para estimar variância populacional sem viés sob as hipóteses usuais.",
    bankApplication: "Em crédito, compare renda, exposição, utilização de limite e atraso por produto e segmento. Média alta de saldo pode ser causada por poucos clientes; mediana e percentis 90/95 mostram o cliente típico e a cauda. O valor de negócio está em dimensionar risco, campanhas e capacidade operacional.",
    cases: ["Concentração de exposição: localizar clientes que dominam o risco da carteira.", "Limites de crédito: comparar distribuição de uso antes de propor aumento.", "Fraude: identificar caudas incomuns sem chamar todo extremo de fraude."],
    pitfalls: ["Confundir estatística descritiva com causalidade", "Usar média em distribuição muito assimétrica sem mostrar quantis", "Remover extremos antes de investigar sua origem"],
    outcomes: ["Distinguir variáveis contínuas e discretas", "Calcular e interpretar posição e dispersão", "Escolher resumos adequados ao negócio", "Explicar como caudas alteram decisões bancárias"],
    project: ["eda-carteira-bancaria", "Diagnóstico executivo de uma carteira bancária", "Construir uma EDA reproduzível que transforme distribuição, dispersão e caudas em decisões de carteira.", ["Relatório de qualidade e estatísticas", "Notebook narrativo com gráficos", "Resumo executivo com cinco decisões"]],
  },
  {
    number: 2, title: "Distribuições, densidade e acumulada", period: "10–16 ago", block: "ESTATÍSTICA BÁSICA", resources: resources.statistics,
    summary: "Aprenda a reconhecer fenômenos Normal, Bernoulli, Binomial, Uniforme, Poisson e Geométrico e a traduzir PMF/PDF/CDF em probabilidades de risco.",
    content: ["PMF, PDF e CDF: significado e propriedades", "Bernoulli e Binomial para eventos e contagens de sucessos", "Poisson e Geométrica para frequência e espera", "Uniforme e Normal: parâmetros, padronização e quantis", "Ajuste de distribuição, simulação Monte Carlo e limites de hipótese"],
    foundation: "Distribuições são modelos para a incerteza. A PMF atribui massa a valores discretos, a PDF descreve densidade para variáveis contínuas e a CDF entrega P(X≤x) em ambos os casos. Cada família impõe hipóteses sobre suporte, independência, taxa e formato; escolher pela aparência do histograma é insuficiente.",
    mechanism: "Identifique primeiro o tipo do fenômeno: evento binário, número de sucessos em n tentativas, contagem por intervalo, tentativas até o primeiro evento ou medida contínua. Estime parâmetros, compare momentos e quantis e faça diagnóstico. Simulação permite verificar se uma regra de risco se comporta sob cenários plausíveis.",
    formula: "F(x)=P(X\\le x),\\qquad P(X=k)_{Bin}=\\binom{n}{k}p^k(1-p)^{n-k},\\qquad Z=\\frac{X-\\mu}{\\sigma}",
    mathExplanation: "A CDF acumula probabilidade; sua diferença entre dois pontos dá probabilidade de intervalo. A Binomial soma n Bernoullis independentes com p constante. A padronização Normal mede quantos desvios-padrão um valor está da média.",
    bankApplication: "Bernoulli representa default; Binomial, número de defaults numa amostra simplificada; Poisson, frequência de chamadas ou alertas por janela; Geométrica, tentativas até um evento; Normal pode aproximar erros agregados, mas raramente descreve perdas com cauda pesada. Os modelos apoiam provisionamento, filas e testes de estresse.",
    cases: ["Provisionamento: simular quantidade de defaults sob diferentes probabilidades.", "Operações: dimensionar atendentes a partir de chegadas por intervalo.", "Antifraude: converter score em probabilidade acumulada e percentil."],
    pitfalls: ["Assumir independência quando clientes compartilham fatores macroeconômicos", "Usar Normal para perdas com cauda pesada sem diagnóstico", "Confundir densidade com probabilidade pontual em variável contínua"],
    outcomes: ["Escolher distribuição a partir do mecanismo gerador", "Calcular probabilidades com PMF/PDF/CDF", "Interpretar parâmetros e quantis", "Simular e confrontar teoria com amostra"],
    project: ["simulador-distribuicoes-risco", "Laboratório de distribuições de risco", "Simular fenômenos bancários e validar momentos, probabilidades acumuladas e hipóteses de seis distribuições.", ["Simulador reprodutível", "Comparação teoria versus Monte Carlo", "Mapa de escolha de distribuição"]],
  },
  {
    number: 3, title: "Testes de hipóteses e decisão", period: "17–23 ago", block: "ESTATÍSTICA BÁSICA", resources: resources.statistics,
    summary: "Transforme uma pergunta bancária em hipótese, estatística de teste, incerteza e decisão, separando significância estatística de impacto econômico.",
    content: ["Hipótese nula, alternativa e estatística de teste", "Erros tipo I e II, alfa, beta e poder", "p-valor, intervalo de confiança e tamanho de efeito", "Testes de média, proporção, associação e alternativas não paramétricas", "Desenho de experimento, tamanho amostral e múltiplas comparações"],
    foundation: "Um teste confronta dados com uma hipótese nula por meio da distribuição de uma estatística sob H0. O p-valor não é a probabilidade de H0 ser verdadeira. Alfa controla falso positivo no desenho; poder mede chance de detectar um efeito relevante. Intervalo e tamanho de efeito informam magnitude, essencial para decisão.",
    mechanism: "Defina antes dos dados: unidade, população, métrica primária, efeito mínimo relevante, H0/H1, alfa e regra de decisão. Verifique independência, distribuição e balanceamento; execute o teste adequado; relate estimativa, intervalo, p-valor e impacto de negócio. Em observacional, não prometa causalidade.",
    formula: "z=\\frac{\\hat p_1-\\hat p_2}{SE(\\hat p_1-\\hat p_2)},\\qquad IC=\\hat\\theta\\pm z_{1-\\alpha/2}SE(\\hat\\theta)",
    mathExplanation: "A estatística padroniza o efeito observado pelo erro-padrão. Quanto maior a amostra, menor o erro-padrão; por isso efeitos irrelevantes podem ser significativos. O intervalo mostra valores compatíveis com os dados e o procedimento.",
    bankApplication: "Teste uma política de aumento de limite comparando conversão e inadimplência, mantendo inadimplência como métrica de proteção. O banco precisa decidir se o ganho esperado supera perdas, custo de capital e risco regulatório, não apenas se p<0,05.",
    cases: ["A/B de oferta de crédito com conversão e default como guardrail.", "Comparação de taxa de fraude antes/depois sem ignorar sazonalidade.", "Mudança de cobrança avaliada por recuperação líquida e reclamações."],
    pitfalls: ["P-hacking e escolha de hipótese depois de ver o resultado", "Confundir associação observacional com efeito causal", "Ignorar tamanho de efeito, poder e múltiplos testes"],
    outcomes: ["Formular H0/H1 e regra de decisão", "Interpretar p-valor e intervalo corretamente", "Escolher teste e verificar hipóteses", "Conectar resultado ao custo bancário"],
    project: ["experimento-politica-credito", "Experimento de política de crédito", "Avaliar se uma nova política aumenta conversão sem elevar inadimplência além da tolerância.", ["Plano pré-experimento", "Análise estatística reproduzível", "Memorando lançar/não lançar/coletar mais"]],
  },
  {
    number: 4, title: "Vetores, matrizes e distâncias", period: "24–30 ago", block: "ÁLGEBRA", resources: resources.algebra,
    summary: "Domine a representação vetorial dos dados, operações matriciais, produto interno e distâncias que sustentam modelos, similaridade e otimização.",
    content: ["Vetores, matrizes, dimensão, transposição e combinação linear", "Soma, multiplicação, inversa, determinante, posto e sistemas lineares", "Produto interno, norma, ortogonalidade e projeção", "Distâncias Euclidiana, Manhattan, Minkowski, cosseno e Mahalanobis", "Escala, correlação, singularidade e interpretação geométrica"],
    foundation: "Uma linha pode representar um cliente e cada coluna uma feature; a matriz organiza toda a carteira. Multiplicação matricial combina transformações. Produto interno mede alinhamento, norma mede magnitude e distância formaliza proximidade. Posto e condicionamento revelam redundância e instabilidade.",
    mechanism: "Antes de medir proximidade, defina escala, semântica e correlação das variáveis. Euclidiana favorece geometria esférica; Manhattan é mais robusta em certas dimensões; cosseno ignora magnitude; Mahalanobis incorpora covariância. Operações devem respeitar dimensões e hipóteses numéricas.",
    formula: "\\langle x,y\\rangle=x^Ty,\\qquad d_2(x,y)=\\sqrt{(x-y)^T(x-y)},\\qquad d_M=\\sqrt{(x-y)^T\\Sigma^{-1}(x-y)}",
    mathExplanation: "Produto interno gera norma e ângulo. Mahalanobis reescala diferenças pela matriz de covariância, reduzindo peso de direções naturalmente variáveis, mas exige estimativa estável e invertível de Σ.",
    bankApplication: "Representações vetoriais permitem encontrar clientes semelhantes, medir distância a um perfil de fraude e resolver regressão ou otimização. Sem padronização, renda pode dominar idade; sem tratar correlação, variáveis duplicadas contam duas vezes.",
    cases: ["Similaridade de clientes para próxima melhor oferta.", "Distância a padrões conhecidos de fraude.", "Matrizes de transição e exposições em risco de crédito."],
    pitfalls: ["Comparar variáveis em escalas incompatíveis", "Inverter matriz singular sem diagnóstico", "Interpretar proximidade matemática como equivalência de negócio"],
    outcomes: ["Executar operações matriciais", "Interpretar produto interno e projeções", "Escolher e calcular distâncias", "Explicar escala e condicionamento"],
    project: ["motor-similaridade-clientes", "Motor auditável de similaridade", "Comparar métricas de distância e mostrar como escala e correlação mudam o ranking de clientes.", ["Biblioteca de distâncias testada", "Ranking comparativo", "Nota técnica de escolha da métrica"]],
  },
  {
    number: 5, title: "Missings, outliers e categorização", period: "31 ago–06 set", block: "DATA PREP", resources: resources.dataPrep,
    summary: "Construa tratamento de dados que preserve sinal, seja aprendido apenas no treino e deixe explícitos os efeitos de ausência, extremos e codificação.",
    content: ["Tipos e mecanismos de missing: MCAR, MAR e MNAR", "Imputação simples, por grupo, multivariada e indicador de ausência", "Detecção e tratamento de outliers por regra, robustez e contexto", "Binning, one-hot, ordinal, frequência e categorias raras", "Pipeline, fit/transform, leakage e auditoria antes/depois"],
    foundation: "Missing e outlier não são apenas sujeira: podem carregar informação do processo. MCAR, MAR e MNAR pedem interpretações diferentes. Categorização altera representação e viés. Toda estatística de tratamento deve ser aprendida no treino e aplicada aos demais conjuntos.",
    mechanism: "Faça diagnóstico por coluna, período e segmento; investigue causa operacional; escolha tratamento compatível com o modelo; encapsule em Pipeline/ColumnTransformer; compare distribuição e métrica antes/depois. Conserve flags e trilha de decisão quando ausência ou cap tiver sentido de negócio.",
    formula: "IQR=Q_3-Q_1,\\qquad limite=[Q_1-1.5IQR,\\;Q_3+1.5IQR],\\qquad z_i=\\frac{x_i-\\mu}{\\sigma}",
    mathExplanation: "IQR fornece regra robusta baseada nos 50% centrais; z-score supõe escala e é sensível aos próprios extremos. Regras estatísticas sinalizam pontos para investigação, não decretam erro automaticamente.",
    bankApplication: "Renda ausente pode indicar canal ou perfil específico; transação extrema pode ser fraude ou cliente private; categorias raras podem ser eventos de risco. A decisão deve considerar custo de perder sinal, estabilidade e exigência de explicação.",
    cases: ["Imputar renda sem usar informação do período futuro.", "Tratar transação extrema mantendo flag para antifraude.", "Agrupar ocupações raras com regra estável para produção."],
    pitfalls: ["Imputar antes do split", "Remover todo outlier por regra automática", "Codificar categoria ordinal como número sem ordem real"],
    outcomes: ["Diagnosticar mecanismo de ausência", "Escolher tratamento justificável", "Montar pipeline sem leakage", "Auditar efeito por segmento"],
    project: ["pipeline-qualidade-credito", "Pipeline de qualidade para crédito", "Criar preprocessing reproduzível para missings, outliers e categorias com testes contra leakage.", ["Relatório de qualidade", "Pipeline serializável", "Testes de schema e não vazamento"]],
  },
  {
    number: 6, title: "Associação, PCA e seleção de variáveis", period: "07–13 set", block: "DATA PREP", resources: resources.dataPrep,
    summary: "Reduza redundância e dimensionalidade usando associação, PCA e seleção de features sem contaminar validação ou sacrificar estabilidade.",
    content: ["Pearson, Spearman e associação não linear", "Qui-quadrado, V de Cramér e associação entre categóricas", "PCA: escala, covariância, autovetores, scores e loadings", "Seleção filter, wrapper e embedded", "Estabilidade temporal, multicolinearidade, custo e leakage de seleção"],
    foundation: "Correlação mede padrão de associação, não causalidade. PCA encontra direções ortogonais de maior variância após centralização/escala. Seleção de variáveis busca sinal preditivo, estabilidade e custo operacional; deve ocorrer dentro de cada fold.",
    mechanism: "Classifique tipos das variáveis, escolha medida de associação, investigue redundância e temporalidade. Para PCA, padronize quando escalas diferirem, ajuste apenas no treino e interprete loadings. Compare filtros, RFE e métodos embedded sob protocolo de validação comum.",
    formula: "R=Q\\Lambda Q^T,\\qquad Z=XQ_k,\\qquad V=\\sqrt{\\frac{\\chi^2/n}{\\min(r-1,c-1)}}",
    mathExplanation: "A decomposição espectral da matriz de correlação produz autovetores (direções) e autovalores (variância explicada). V de Cramér normaliza qui-quadrado para medir força de associação categórica.",
    bankApplication: "Reduza centenas de sinais de bureau ou transações mantendo performance e custo. PCA pode ajudar em compressão e anomalia, mas dificulta explicação regulatória. Seleção estável melhora implantação, monitoramento e resistência a mudanças de população.",
    cases: ["Eliminar features duplicadas de bureau sem perder desempenho.", "Comprimir comportamento transacional para detecção de anomalia.", "Selecionar variáveis disponíveis no momento real da decisão."],
    pitfalls: ["Selecionar usando todo o dataset", "Interpretar correlação como causalidade", "Escolher PCA apenas pela variância sem validar utilidade"],
    outcomes: ["Escolher medida de associação por tipo", "Explicar PCA matematicamente", "Comparar métodos de seleção", "Medir estabilidade e custo de features"],
    project: ["selecao-features-estavel", "Laboratório de features estáveis", "Comparar associação, PCA e seleção de variáveis em uma carteira com corte temporal.", ["Mapa de associações", "Experimento com e sem PCA", "Feature list com custo e estabilidade"]],
  },
  {
    number: 7, title: "Programação para ciência de dados", period: "14–20 set", block: "PROGRAMAÇÃO", resources: resources.programming,
    summary: "Ganhe fluência em Python, entrada/saída de dados e scikit-learn construindo código modular, testável e executável fora do notebook.",
    content: ["Tipos, coleções, controle de fluxo, funções, módulos e exceções", "Comprehensions, iteradores, contexto e orientação a objetos essencial", "Leitura/escrita CSV, JSON, Parquet e SQL com pandas", "APIs estimator, fit, transform, predict e Pipeline no scikit-learn", "Ambientes, logging, testes, tipagem, lint e empacotamento"],
    foundation: "Fluência significa decompor problemas em funções com entradas, saídas e erros claros, conhecer estruturas básicas e usar bibliotecas sem esconder o fluxo. pandas representa tabelas; scikit-learn padroniza estimadores e pipelines; o ambiente registra dependências.",
    mechanism: "Explore em notebook, mova lógica estável para src/, escreva docstrings e testes, trate erros de I/O, configure logging e exponha comando reproduzível. Pipeline une transformações e modelo, evitando diferenças entre treino e inferência.",
    formula: "pipeline: X \\xrightarrow{fit/transform} Z \\xrightarrow{fit/predict} \\hat y",
    mathExplanation: "Mesmo sendo uma semana de programação, a interface preserva o fluxo matemático: transformações aprendem parâmetros no treino e o estimador mapeia features para uma saída. Separar fit de transform/predict é central contra leakage.",
    bankApplication: "Rotinas robustas leem arquivos de parceiros, validam schema, calculam features e entregam scores de forma rastreável. Código de risco precisa falhar de modo explícito, registrar versão e produzir o mesmo resultado sob a mesma entrada.",
    cases: ["CLI para auditar arquivo de carteira recebido.", "Pipeline de scoring reaproveitado em batch e API.", "Leitura segura de CSV/Parquet com validação de schema."],
    pitfalls: ["Manter regra crítica apenas em notebook", "Capturar exceções sem informar causa", "Versionar segredo, ambiente virtual ou base sensível"],
    outcomes: ["Programar com funções e módulos", "Ler/escrever dados de modo seguro", "Usar API do scikit-learn", "Testar e documentar um pacote"],
    project: ["cli-auditoria-dados", "CLI de auditoria de arquivos", "Transformar notebooks em uma ferramenta instalável que valida e resume arquivos tabulares.", ["Pacote src instalável", "CLI documentada", "Testes e release v1.0.0"]],
  },
  {
    number: 8, title: "Banco de dados relacional e SQL", period: "21–27 set", block: "BANCO DE DADOS", resources: resources.database,
    summary: "Modele dados relacionais e escreva SQL correto, auditável e temporalmente seguro para construir a visão cliente-data.",
    content: ["Entidades, atributos, relacionamentos e normalização", "PK, chave candidata/secundária e FK", "SELECT, WHERE, CASE, GROUP BY, HAVING e ORDER BY", "INNER/LEFT joins, CTEs, subqueries e funções de janela", "Granularidade, cardinalidade, integridade e prevenção de leakage temporal"],
    foundation: "O modelo relacional representa fatos em relações com esquema e restrições. Chave primária identifica tupla; estrangeira mantém referência; chaves candidatas/alternativas também garantem unicidade. Álgebra relacional sustenta seleção, projeção, junção e agregação.",
    mechanism: "Defina a granularidade antes do SQL, desenhe entidades e cardinalidades, crie constraints e só então componha CTEs. Audite contagem antes/depois de joins, unicidade da chave final, nulos introduzidos e datas disponíveis na referência.",
    formula: "R \\bowtie_{R.chave=S.chave} S,\\qquad \\gamma_{cliente;\\,SUM(valor)}(Transacoes)",
    mathExplanation: "Join combina tuplas segundo predicado; agregação particiona relações por chave e calcula medidas. Se ambos os lados tiverem duplicatas, um N:M multiplica linhas e totais, mesmo quando a query executa sem erro.",
    bankApplication: "Um mart cliente-mês combina cadastro, contas, transações e pagamentos. Granularidade e data de corte evitam duplicar exposição e usar pagamentos futuros no treino de default.",
    cases: ["Mart cliente-mês para risco de crédito.", "Reconciliação entre transações e saldo contábil.", "Features de 30/60/90 dias respeitando data de referência."],
    pitfalls: ["Join N:M acidental", "Selecionar coluna não agregada sem semântica", "Usar evento futuro como feature"],
    outcomes: ["Desenhar modelo relacional", "Escrever queries com joins/agregações", "Auditar chaves e cardinalidade", "Construir features temporais seguras"],
    project: ["mart-cliente-mes", "Mart cliente-mês auditável", "Construir em DuckDB um mart de features com ERD, constraints, reconciliação e testes temporais.", ["ERD e DDL", "Pipeline SQL idempotente", "Testes de PK/FK e leakage"]],
  },
  {
    number: 9, title: "Métricas e validação de modelos", period: "28 set–04 out", block: "AVALIAÇÃO DE MODELOS", resources: resources.evaluation,
    summary: "Escolha métricas e validações pela decisão bancária, separando regressão, classificação, ranking, calibração, corte temporal e custo.",
    content: ["RMSE, MAE e R² para alvos contínuos", "Precision, Recall e F1 sob classes desbalanceadas", "ROC-AUC, KS e Gini como discriminação/ranking", "Holdout, leave-one-out, k-fold, out-of-sample e out-of-time", "Threshold, calibração, matriz de custo, segmentos e incerteza"],
    foundation: "Métrica resume um aspecto do erro e não existe vencedora universal. MAE mede erro absoluto típico; RMSE penaliza erros grandes; R² compara à variabilidade. Precision e recall dependem do threshold e prevalência. AUC/KS/Gini medem ordenação, não calibração nem benefício econômico.",
    mechanism: "Defina unidade, janela, baseline e custo; separe treino/validação/teste; use OOT quando produção enfrenta futuro; faça seleção apenas na validação; abra teste uma vez; reporte intervalos e resultados por segmento. Threshold nasce da capacidade e do custo.",
    formula: "RMSE=\\sqrt{\\frac1n\\sum(y_i-\\hat y_i)^2},\\quad F1=2\\frac{PR}{P+R},\\quad Gini=2AUC-1",
    mathExplanation: "RMSE eleva resíduos ao quadrado; F1 é média harmônica de precision e recall; Gini é transformação linear da AUC para um classificador binário. KS é a maior distância entre CDFs dos scores de positivos e negativos.",
    bankApplication: "Em fraude, recall precisa respeitar orçamento de alertas; em crédito, AUC alta não garante PD calibrada; em previsão de perda, RMSE pode priorizar grandes erros. OOT simula mudança macroeconômica e evita uma confiança inflada por split aleatório.",
    cases: ["Escolher threshold antifraude sob capacidade diária.", "Validar PD com discriminação e calibração.", "Comparar previsão de recuperação com MAE/RMSE por faixa."],
    pitfalls: ["Otimizar no conjunto de teste", "Usar accuracy em classe rara", "Comparar AUC de janelas/populações incompatíveis"],
    outcomes: ["Calcular e interpretar todas as métricas oficiais", "Escolher validação adequada", "Definir threshold por custo", "Explicar diferença entre ranking e calibração"],
    project: ["laboratorio-metricas-validacao", "Laboratório de métricas e validação", "Construir um comparador que demonstre como métrica, threshold e split mudam a decisão bancária.", ["Biblioteca de métricas testada", "Comparação holdout/k-fold/OOT", "Matriz de custo e recomendação"]],
  },
  {
    number: 10, title: "Regressão linear e resíduos", period: "05–11 out", block: "REGRESSÃO", resources: resources.regression,
    summary: "Modele um alvo contínuo com regressão linear, interprete coeficientes com cautela e use resíduos para descobrir violações e segmentos mal atendidos.",
    content: ["Modelo linear, intercepto, coeficientes e mínimos quadrados", "Hipóteses de linearidade, independência, homocedasticidade e normalidade dos erros", "Resíduos, leverage, influência e heterocedasticidade", "Intervalos de confiança e de predição", "Baseline, extrapolação, colinearidade e validação temporal"],
    foundation: "Regressão linear estima a média condicional como combinação linear das features. OLS minimiza soma dos resíduos quadráticos. Coeficiente é associação condicional ao conjunto de variáveis, não efeito causal automático. Diagnóstico verifica se inferência e predição são confiáveis.",
    mechanism: "Defina alvo e corte temporal, crie baseline, ajuste pipeline, inspecione resíduos versus ajustados, QQ-plot, leverage e estabilidade. Compare MAE/RMSE/R² globalmente e por segmento. Transforme alvo ou use erros robustos se houver justificativa.",
    formula: "\\hat\\beta=(X^TX)^{-1}X^Ty,\\qquad e=y-X\\hat\\beta,\\qquad R^2=1-\\frac{SS_{res}}{SS_{tot}}",
    mathExplanation: "Equações normais projetam y no espaço gerado por X quando XᵀX é invertível. Resíduo é a parte não explicada; R² mede redução relativa da soma de quadrados, mas pode aumentar com variáveis inúteis.",
    bankApplication: "Preveja gasto, limite adequado ou valor recuperado e examine onde o modelo erra. Resíduos maiores em baixa renda podem indicar forma funcional ruim ou feature ausente e produzir decisões injustas.",
    cases: ["Previsão de gasto mensal para capacidade de pagamento.", "Estimativa de recuperação em cobrança.", "Análise de resíduos por segmento e período."],
    pitfalls: ["Interpretar coeficiente como causal", "Usar R² como única evidência", "Ignorar extrapolação e heterocedasticidade"],
    outcomes: ["Derivar e interpretar OLS", "Diagnosticar resíduos", "Comparar métricas e baseline", "Comunicar limitações para decisão"],
    project: ["regressao-gasto-residuos", "Previsão de gasto com diagnóstico", "Prever gasto fora do tempo e transformar resíduos em diagnóstico de risco e equidade.", ["Modelo e baseline", "Painel de resíduos", "Relatório por segmento/período"]],
  },
  {
    number: 11, title: "Regularização, árvore e GLM", period: "12–18 out", block: "REGRESSÃO", resources: resources.regression,
    summary: "Compare L1/L2, árvore de regressão e GLMs, entendendo vieses, famílias, funções de ligação e governança do champion/challenger.",
    content: ["Ridge/L2, Lasso/L1, escala e caminho de regularização", "Árvore de regressão, partições, MSE, poda e overfitting", "GLM: componente aleatório, preditor linear e função de ligação", "Famílias Gaussiana, Binomial, Poisson e Gamma", "Tuning aninhado, estabilidade, explicabilidade e escolha champion/challenger"],
    foundation: "Regularização adiciona penalidade para reduzir variância; L1 pode zerar coeficientes e L2 os encolhe. Árvores aproximam relações não lineares por regiões. GLMs estendem o preditor linear a distribuições da família exponencial por uma função de ligação.",
    mechanism: "Padronize quando necessário, ajuste hiperparâmetros apenas na validação, compare no mesmo split e avalie estabilidade. Para GLM, escolha família pelo suporte/variância do alvo e verifique dispersão. Para árvore, limite complexidade e examine folhas.",
    formula: "\\min_\\beta RSS+\\lambda\\lVert\\beta\\rVert_1\\;ou\\;RSS+\\lambda\\lVert\\beta\\rVert_2^2,\\qquad g(E[Y|X])=X\\beta",
    mathExplanation: "λ controla compromisso viés-variância. L1 tem geometria que favorece soluções esparsas; L2 estabiliza coeficientes correlacionados. No GLM, g liga média condicional ao preditor linear.",
    bankApplication: "Lasso ajuda a reduzir features de score; Ridge estabiliza sinais correlacionados; árvore captura regras; Poisson/Gamma modelam contagem ou severidade. O banco compara performance com transparência, estabilidade e custo operacional.",
    cases: ["Severidade de perda com GLM Gamma.", "Contagem de ocorrências com GLM Poisson.", "Champion/challenger Ridge, Lasso e árvore."],
    pitfalls: ["Regularizar sem escalar", "Escolher família/link incompatível", "Deixar árvore crescer até memorizar treino"],
    outcomes: ["Comparar L1 e L2", "Controlar árvore de regressão", "Especificar e diagnosticar GLM", "Defender champion/challenger"],
    project: ["champion-regressao-severidade", "Champion/challenger de severidade", "Comparar regularização, árvore e GLM para prever perda com estabilidade e explicabilidade.", ["Pipeline comum", "Tabela champion/challenger", "Model card do vencedor"]],
  },
  {
    number: 12, title: "Logística e Naive Bayes", period: "19–25 out", block: "CLASSIFICAÇÃO", resources: resources.classification,
    summary: "Estime probabilidade de evento com regressão logística e Naive Bayes, distinguindo log-odds, independência condicional, calibração e threshold.",
    content: ["Regressão logística, sigmoid, odds, log-odds e máxima verossimilhança", "Interpretação de coeficientes e odds ratio", "Naive Bayes Gaussiano, Bernoulli e Multinomial", "Independência condicional e suavização", "Probabilidade, calibração, discriminação, threshold e custo"],
    foundation: "Logística modela log-odds como função linear e estima parâmetros por máxima verossimilhança. Naive Bayes aplica Bayes assumindo independência condicional das features dada a classe; mesmo irreal, pode funcionar bem e é baseline eficiente.",
    mechanism: "Prepare features em pipeline, defina split temporal e baseline, ajuste modelos, compare AUC/KS e calibração, examine coeficientes/verossimilhanças e escolha threshold pelo custo. Valide estabilidade e grupos.",
    formula: "P(Y=1|x)=\\sigma(\\beta_0+x^T\\beta),\\quad log\\frac{p}{1-p}=\\beta_0+x^T\\beta,\\quad P(y|x)\\propto P(y)\\prod_jP(x_j|y)",
    mathExplanation: "Sigmoid mapeia reais em probabilidade. e^β é multiplicador das odds para uma unidade, mantidas outras features. Naive Bayes multiplica verossimilhanças condicionais e priori, normalmente no log para estabilidade.",
    bankApplication: "Regressão logística é referência para PD pela transparência; Naive Bayes serve a triagem rápida de texto/eventos. O score ordena, a calibração estima probabilidade e o threshold implementa a política.",
    cases: ["Probabilidade de inadimplência com logística.", "Triagem de mensagens suspeitas com Naive Bayes.", "Threshold de aprovação sob custo esperado."],
    pitfalls: ["Interpretar probabilidade não calibrada como PD", "Confundir coeficiente com variação direta em p", "Ignorar dependência forte no Naive Bayes"],
    outcomes: ["Derivar logística e Bayes", "Interpretar odds ratio", "Avaliar calibração", "Escolher threshold por custo"],
    project: ["pd-logistica-naive-bayes", "PD com logística e Naive Bayes", "Estimar inadimplência e escolher um threshold defendido por custo, discriminação e calibração.", ["Dois pipelines comparáveis", "Curvas e calibração", "Política de threshold"]],
  },
  {
    number: 13, title: "KNN e SVM", period: "26 out–01 nov", block: "CLASSIFICAÇÃO", resources: resources.classification,
    summary: "Entenda aprendizagem por vizinhança e margem máxima, incluindo escala, kernels, dimensionalidade, latência e custo de erro.",
    content: ["KNN: vizinhos, K, voto, pesos e métricas de distância", "Escala, maldição da dimensionalidade e custo de inferência", "SVM: hiperplano, margem, vetores de suporte e soft margin", "Kernel trick, C e gamma", "Tuning, probabilidade/calibração e comparação operacional"],
    foundation: "KNN prevê a partir dos exemplos próximos e quase não treina, mas armazena dados e sofre em alta dimensão. SVM procura hiperplano de margem máxima; slack permite erros e kernels representam fronteiras não lineares por produtos internos implícitos.",
    mechanism: "Padronize dentro do pipeline, tune K/distância/pesos ou C/kernel/gamma em validação, meça PR-AUC/recall no orçamento e também memória e latência. Use OOT e calibração se a decisão exigir probabilidade.",
    formula: "\\hat y=mode\\{y_i:i\\in N_k(x)\\},\\qquad \\min_{w,b}\\frac12\\lVert w\\rVert^2+C\\sum_i\\xi_i",
    mathExplanation: "KNN usa a geometria escolhida; em SVM, minimizar norma maximiza margem, enquanto C penaliza violações. Kernel substitui produto interno por similaridade em espaço transformado.",
    bankApplication: "Compare KNN e SVM para fraude: KNN encontra padrões locais, SVM separa classes complexas. Produção precisa considerar milhões de transações, explicação, memória e tempo de resposta, não apenas AUC.",
    cases: ["Fraude por vizinhança de transações.", "SVM para fronteira não linear de risco.", "Benchmark de latência e recall sob fila limitada."],
    pitfalls: ["Esquecer padronização", "Tunar no teste", "Usar KNN em alta dimensão/volume sem medir latência"],
    outcomes: ["Explicar KNN e SVM matematicamente", "Tunar hiperparâmetros", "Avaliar escala e dimensionalidade", "Defender escolha operacional"],
    project: ["knn-svm-fraude", "KNN versus SVM em fraude", "Comparar desempenho e custo operacional para detectar fraude em dados desbalanceados.", ["Pipelines tunados", "Benchmark de métrica/latência", "Recomendação operacional"]],
  },
  {
    number: 14, title: "Árvores, Random Forest e Boosting", period: "02–08 nov", block: "CLASSIFICAÇÃO", resources: resources.classification,
    summary: "Compare árvore, bagging e boosting para risco, dominando impuridade, variância, viés, tuning e explicações responsáveis.",
    content: ["Árvore: splits, Gini/entropia, folhas, profundidade e poda", "Random Forest: bootstrap, aleatoriedade de features e redução de variância", "AdaBoost e Gradient Boosting: erro sequencial e função de perda", "Importância por impuridade e permutation importance", "Tuning, calibração, estabilidade, latência e governança"],
    foundation: "Árvore particiona recursivamente o espaço para aumentar pureza. Random Forest agrega árvores descorrelacionadas por bagging. Boosting soma learners fracos sequencialmente para corrigir erros. Flexibilidade alta exige regularização e validação forte.",
    mechanism: "Fixe splits e orçamento de tuning, comece por árvore interpretável, compare floresta e boosting, use múltiplas métricas e calibração, examine importâncias com cautela e erros por período/segmento.",
    formula: "Gini(t)=1-\\sum_kp_{k,t}^2,\\qquad F_M(x)=F_{M-1}(x)+\\eta h_M(x)",
    mathExplanation: "Split maximiza redução ponderada de impuridade. No gradient boosting, cada novo learner aproxima o gradiente negativo da perda e η controla tamanho do passo.",
    bankApplication: "Ensembles dominam muitos problemas tabulares de crédito/fraude, mas o banco precisa explicar variáveis, estabilidade e ação adversa. Champion deve equilibrar perda esperada, calibração, latência e governança.",
    cases: ["Score de risco com árvore explicável.", "Random Forest como challenger robusto.", "Gradient Boosting para ranking com monitoramento."],
    pitfalls: ["Confiar em feature importance por impuridade", "Comparar modelos com tuning desigual", "Ignorar calibração e mudança temporal"],
    outcomes: ["Explicar split e ensembles", "Distinguir bagging de boosting", "Interpretar importâncias", "Escolher champion governável"],
    project: ["ensembles-risco-credito", "Ensembles para risco de crédito", "Comparar árvore, Random Forest, AdaBoost e Gradient Boosting sob o mesmo protocolo.", ["Benchmark reproduzível", "Análise de importância/erros", "Relatório champion/challenger"]],
  },
  {
    number: 15, title: "Redes neurais", period: "09–15 nov", block: "CLASSIFICAÇÃO", resources: resources.classification,
    summary: "Entenda perceptron multicamadas, backpropagation, regularização e por que uma rede pode ou não agregar valor em dados bancários tabulares.",
    content: ["Neurônio, pesos, bias e funções de ativação", "Camadas, forward pass e capacidade de representação", "Loss, gradiente, backpropagation e otimizadores", "Overfitting, dropout, regularização, batch e early stopping", "Calibração, seeds, baseline tabular e custo de produção"],
    foundation: "Uma rede compõe transformações lineares e não lineares. Forward calcula predição; backprop aplica regra da cadeia para gradientes; otimizador atualiza pesos. Capacidade elevada aprende interações, mas aumenta dados, tuning e governança necessários.",
    mechanism: "Defina baseline forte, normalize dados, separe validação e teste, monitore curvas de loss, use early stopping/dropout e múltiplas seeds. Compare discriminação, calibração, latência e manutenção.",
    formula: "a^{(l)}=\\phi(W^{(l)}a^{(l-1)}+b^{(l)}),\\qquad W\\leftarrow W-\\eta\\nabla_W L",
    mathExplanation: "Cada camada aplica transformação afim e ativação. Regra da cadeia propaga derivadas da perda; η define tamanho da atualização. Ativações permitem aproximar relações não lineares.",
    bankApplication: "MLP pode capturar interações em fraude ou propensão, mas em tabular pequeno ensembles frequentemente vencem. A escolha exige ganho material, calibração, explicação, estabilidade e infraestrutura compatível.",
    cases: ["MLP challenger para inadimplência.", "Curvas de treino para diagnosticar overfitting.", "Comparação de latência e calibração com ensemble."],
    pitfalls: ["Usar rede sem baseline", "Avaliar uma única seed", "Confundir loss baixa com benefício econômico"],
    outcomes: ["Explicar forward/backprop", "Configurar e regularizar MLP", "Diagnosticar curvas", "Defender quando não usar rede"],
    project: ["mlp-challenger-risco", "MLP como challenger tabular", "Testar se uma rede agrega valor real sobre logística e boosting em risco bancário.", ["MLP reproduzível", "Curvas e múltiplas seeds", "Decisão usar/não usar"]],
  },
  {
    number: 16, title: "K-means, K-medoids e número de clusters", period: "16–22 nov", block: "AGRUPAMENTO", resources: resources.clustering,
    summary: "Crie segmentos acionáveis com K-means/K-medoids e escolha K combinando geometria, estabilidade e valor bancário.",
    content: ["Objetivo do clustering e ausência de rótulo", "K-means, centroides, atribuição e atualização", "K-medoids, robustez e custo", "Elbow, silhouette, gap statistic e estabilidade", "Escala, outliers, profiling e acionabilidade"],
    foundation: "K-means minimiza soma de quadrados dentro dos clusters e favorece grupos aproximadamente esféricos. K-medoids usa observações reais como centros e tolera melhor extremos. Índices internos não substituem estabilidade e utilidade.",
    mechanism: "Escolha features comportamentais, trate escala/outliers, rode várias inicializações e K, compare inércia/silhouette/estabilidade e só depois nomeie perfis. Valide em outra janela.",
    formula: "\\min_{C_1,\\dots,C_K}\\sum_{k=1}^K\\sum_{x_i\\in C_k}\\lVert x_i-\\mu_k\\rVert^2,\\qquad s(i)=\\frac{b(i)-a(i)}{\\max(a(i),b(i))}",
    mathExplanation: "O objetivo alterna atribuição e atualização até convergir a mínimo local. Silhouette compara coesão a(i) e separação b(i), variando de −1 a 1.",
    bankApplication: "Segmente clientes por comportamento para comunicação, retenção ou oferta. Cluster só tem valor se for estável, explicável, grande o suficiente e associado a ação; não deve substituir política de risco supervisionada.",
    cases: ["Segmentação de uso de cartões.", "Escolha de K por estabilidade e campanha.", "Comparação de centroides e medoids para extremos."],
    pitfalls: ["Escolher K só pelo elbow", "Nomear cluster antes do profiling", "Usar variáveis de escala incompatível"],
    outcomes: ["Implementar K-means/K-medoids", "Escolher K com múltiplos critérios", "Medir estabilidade", "Criar playbook de ação"],
    project: ["segmentacao-clientes-acionavel", "Segmentação bancária acionável", "Construir segmentos estáveis e justificar K com métricas, perfil e plano de ação.", ["Comparação K-means/K-medoids", "Relatório de estabilidade", "Playbook por segmento"]],
  },
  {
    number: 17, title: "DBSCAN, hierárquico e GMM", period: "23–29 nov", block: "AGRUPAMENTO", resources: resources.clustering,
    summary: "Compare densidade, hierarquia e mistura probabilística para grupos irregulares, ruído, pertença suave e anomalias.",
    content: ["DBSCAN: eps, min_samples, core, border e noise", "Gráfico k-distance, densidade variável e escala", "Hierárquico aglomerativo, linkage e dendrograma", "GMM, componentes Gaussianos, EM e probabilidades", "AIC/BIC, estabilidade, anomalia e interpretação"],
    foundation: "DBSCAN conecta regiões densas e marca ruído sem exigir K. Hierárquico cria árvore de fusões conforme linkage. GMM supõe mistura de Gaussianas e retorna pertença probabilística, estimada por Expectation-Maximization.",
    mechanism: "Prepare escala/distância, explore k-distance, compare linkages, ajuste GMM com vários componentes/covariâncias e use AIC/BIC. Valide estabilidade, perfis e amostras de ruído antes de chamar anomalia de fraude.",
    formula: "p(x)=\\sum_{k=1}^K\\pi_k\\mathcal N(x|\\mu_k,\\Sigma_k),\\qquad BIC=k\\ln n-2\\ln\\hat L",
    mathExplanation: "GMM pondera densidades por π; EM alterna responsabilidades e atualização dos parâmetros. BIC penaliza log-verossimilhança pela complexidade e tamanho amostral.",
    bankApplication: "DBSCAN pode revelar padrões de transação densos e ruído; hierárquico ajuda taxonomia; GMM fornece probabilidade de segmento. Alertas ainda exigem contexto e revisão humana.",
    cases: ["Ruído transacional como fila de investigação.", "Dendrograma de perfis de empresas.", "Pertença suave para estratégia de relacionamento."],
    pitfalls: ["Tratar noise como fraude confirmada", "Ler dendrograma sem escala/linkage", "Escolher GMM só pelo menor BIC sem interpretação"],
    outcomes: ["Configurar DBSCAN", "Interpretar dendrograma", "Explicar EM/GMM", "Combinar diagnóstico e negócio"],
    project: ["clustering-anomalias-bancarias", "Clustering e anomalias bancárias", "Comparar DBSCAN, hierárquico e GMM para segmentação e triagem de anomalias.", ["Benchmark de algoritmos", "Dendrograma/AIC/BIC", "Fila de investigação explicada"]],
  },
  {
    number: 18, title: "Fundamentos de GenAI e transformers", period: "30 nov–06 dez", block: "IA GENERATIVA", resources: resources.genAi,
    summary: "Domine NLP, tokens, embeddings contextuais, attention, transformer, in-context learning e engenharia de prompt com foco em uso responsável no banco.",
    content: ["IA generativa, NLP, linguagem probabilística, tokens e contexto", "Embeddings contextuais e representação", "Self-attention, multi-head attention e positional encoding", "Transformer, pré-treinamento e geração autoregressiva", "In-context learning e engenharia de prompt"],
    foundation: "Modelos de linguagem estimam distribuição do próximo token e geram sequências. Transformer usa attention para combinar contexto em paralelo. In-context learning condiciona comportamento por instruções e exemplos sem atualizar pesos.",
    mechanism: "Entenda tokenização e janela, acompanhe embeddings por camadas, calcule attention conceitualmente e estruture prompts com papel, tarefa, contexto, restrições, formato, exemplos e critérios de verificação.",
    formula: "Attention(Q,K,V)=softmax\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V,\\qquad P(x)=\\prod_tP(x_t|x_{<t})",
    mathExplanation: "Similaridades QKᵀ são escaladas e normalizadas para ponderar V. O modelo autoregressivo maximiza log-verossimilhança dos próximos tokens, não verdade factual.",
    bankApplication: "LLMs resumem normativos, classificam contatos e apoiam analistas, mas não devem decidir crédito sozinhos. Prompts precisam contexto autorizado, saída estruturada, citações quando cabíveis e rota de revisão humana.",
    cases: ["Resumo assistido de política interna.", "Classificação e minuta de atendimento.", "Copiloto de analista com saída estruturada."],
    pitfalls: ["Confundir fluência com veracidade", "Enviar PII/segredo a serviço não autorizado", "Esperar que prompt elimine risco de alucinação"],
    outcomes: ["Explicar geração autoregressiva", "Derivar attention", "Usar in-context learning", "Projetar prompt verificável"],
    project: ["laboratorio-prompts-bancarios", "Laboratório seguro de prompts", "Criar e avaliar prompts para resumo/classificação bancária com rubric, ataques e revisão humana.", ["Conjunto de testes", "Prompts versionados", "Relatório de qualidade e riscos"]],
  },
  {
    number: 19, title: "RAG, embeddings e alinhamento", period: "07–13 dez", block: "IA GENERATIVA", resources: resources.genAi,
    summary: "Construa a visão completa de RAG, bancos vetoriais, fine-tuning, quantização, RLHF e guardrails, separando técnica, avaliação e governança.",
    content: ["Embeddings, similaridade, chunking, metadados e índices vetoriais", "RAG: ingestão, retrieval, reranking, geração e citações", "Treinamento, instruction tuning, fine-tuning e adaptação eficiente", "Quantization e compromisso memória/latência/qualidade", "RLHF, safeguards, guardrails, avaliação e observabilidade"],
    foundation: "RAG adiciona contexto recuperado sem alterar pesos; fine-tuning altera comportamento/parâmetros, não garante conhecimento atualizado. Quantização reduz precisão numérica. RLHF alinha respostas a preferências. Guardrails formam camadas de prevenção, detecção e resposta.",
    mechanism: "Defina corpus e permissão, segmente com metadados, crie embeddings/índice, avalie retrieval antes da geração e force citação/abstenção. Compare baseline, RAG e fine-tuning; teste ataques, PII, viés, latência e custo.",
    formula: "sim(q,d)=\\frac{q\\cdot d}{\\lVert q\\rVert\\lVert d\\rVert},\\qquad Recall@k=\\frac{|relevantes\\ recuperados@k|}{|relevantes|}",
    mathExplanation: "Similaridade de cosseno ranqueia direção dos embeddings. Recall@k mede cobertura do retrieval; uma resposta pode falhar mesmo com bom retrieval, então avalie contexto e geração separadamente.",
    bankApplication: "RAG pode responder sobre políticas internas com versão, permissão e fonte. Guardrails bloqueiam PII, prompt injection e ação não autorizada; logs e revisão atendem auditoria. Fine-tuning só se justifica por padrão de tarefa estável e dados governados.",
    cases: ["Assistente de políticas com citação e controle de acesso.", "Busca semântica de procedimentos.", "Avaliação de prompt injection, PII e abstenção."],
    pitfalls: ["Avaliar apenas a resposta final", "Indexar documento sem permissão/versão", "Usar fine-tuning para conhecimento que muda"],
    outcomes: ["Desenhar pipeline RAG", "Avaliar retrieval e geração", "Distinguir RAG/fine-tuning", "Projetar guardrails em camadas"],
    project: ["rag-politicas-bancarias", "RAG governado para políticas", "Construir um RAG local com citações, avaliação de retrieval, guardrails e model card.", ["Pipeline de ingestão/retrieval", "Dataset de avaliação", "Threat model e model card"]],
  },
  {
    number: 20, title: "Programação linear e Simplex", period: "14–20 dez", block: "PESQUISA OPERACIONAL", resources: resources.optimization,
    summary: "Formule decisões bancárias como programação linear, interprete região viável e resolva por método gráfico e Simplex.",
    content: ["Variáveis de decisão, função objetivo e restrições", "Linearidade, proporcionalidade, aditividade e divisibilidade", "Forma padrão, região viável, vértices e ótimo", "Solução gráfica em duas variáveis", "Simplex, variáveis de folga, pivoteamento, dualidade e sensibilidade"],
    foundation: "Programação linear otimiza função linear sob restrições lineares contínuas. Se há ótimo finito, existe ótimo em vértice da região viável. Simplex percorre bases/vértices melhorando o objetivo; dualidade atribui valor marginal às restrições.",
    mechanism: "Traduza unidades e decisão, defina variáveis, objetivo e cada restrição, verifique viabilidade/limites, resolva caso pequeno graficamente e depois com solver. Valide solução no problema e interprete preço sombra.",
    formula: "\\max_x c^Tx\\quad s.a.\\quad Ax\\le b,\\;x\\ge0",
    mathExplanation: "c contém retorno/custo por unidade; Ax≤b expressa recursos. Variáveis de folga convertem desigualdades em igualdades. Uma base determina vértice; pivoteamento troca variáveis básicas.",
    bankApplication: "Aloque orçamento de campanhas, capital ou capacidade de atendimento maximizando retorno sob limites de risco, canal e equipe. Sensibilidade informa quanto vale ampliar um recurso.",
    cases: ["Orçamento de campanhas por canal.", "Alocação de capacidade de cobrança.", "Mix de produtos sob limites de capital."],
    pitfalls: ["Omitir unidade ou restrição real", "Usar modelo linear para relação não linear sem justificar", "Aceitar status do solver sem validar solução"],
    outcomes: ["Formular LP", "Resolver graficamente", "Explicar Simplex", "Interpretar dual e sensibilidade"],
    project: ["otimizador-campanhas-lp", "Otimizador linear de campanhas", "Maximizar retorno esperado de campanhas sob orçamento, capacidade e regras de risco.", ["Formulação matemática", "Solução gráfica didática", "Solver e análise de sensibilidade"]],
  },
  {
    number: 21, title: "Programação inteira e Branch-and-Bound", period: "21–27 dez", block: "PROGRAMAÇÃO INTEIRA", resources: resources.optimization,
    summary: "Modele escolhas discretas com variáveis inteiras/binárias e entenda relaxação, arredondamento e Branch-and-Bound sem confundir solução aproximada e prova de ótimo.",
    content: ["Variáveis inteiras e binárias e lógica de decisão", "Restrições de seleção, implicação, exclusão e cardinalidade", "Relaxação linear como bound", "Arredondamento: quando funciona e quando viola restrições", "Branch-and-Bound: ramificação, limites, poda e incumbente"],
    foundation: "Programação inteira restringe parte ou todas as variáveis a valores discretos. A relaxação remove integralidade e fornece limite otimista. Branch-and-Bound divide o espaço e poda nós inviáveis ou incapazes de superar a melhor solução inteira.",
    mechanism: "Defina significado de cada binária, formule lógica linear, resolva relaxação, analise se arredondamento preserva restrições e acompanhe árvore: bound, incumbente e critério de poda. Valide integridade e negócio.",
    formula: "\\max c^Tx\\quad s.a.\\quad Ax\\le b,\\;x_j\\in\\{0,1\\},\\qquad x_a\\le x_b\\;\\text{(implicação)}",
    mathExplanation: "Relaxação admite 0≤x≤1 e amplia região viável; em maximização, seu objetivo limita superiormente o inteiro. A ramificação adiciona x≤⌊x*⌋ ou x≥⌈x*⌉.",
    bankApplication: "Escolha agências, campanhas ou casos de cobrança indivisíveis. Binárias modelam ativar ação e precedência; Branch-and-Bound fornece solução e evidência de qualidade.",
    cases: ["Selecionar clientes para campanha sob orçamento.", "Escalar equipes e turnos inteiros.", "Escolher conjunto de iniciativas com dependências."],
    pitfalls: ["Arredondar e violar orçamento", "Usar Big-M enorme sem limite válido", "Não diferenciar incumbente de bound"],
    outcomes: ["Formular lógica binária", "Usar relaxação como bound", "Explicar Branch-and-Bound", "Validar solução discreta"],
    project: ["selecao-carteira-inteira", "Seleção inteira de carteira", "Selecionar ações de cobrança discretas sob orçamento, capacidade e dependências.", ["Modelo binário", "Comparação relaxação/arredondamento", "Árvore Branch-and-Bound explicada"]],
  },
  {
    number: 22, title: "MIP, GAP, Best Bound e solvers", period: "28–31 dez", block: "MIP (MIXED INTEGER PROGRAM)", resources: resources.optimization,
    summary: "Integre variáveis contínuas e inteiras em MIP, interprete incumbente, Best Bound e GAP e opere solvers de forma reproduzível.",
    content: ["MIP: combinação de variáveis contínuas, inteiras e binárias", "Modelagem de ligação, capacidade, ativação e piecewise linear", "Incumbente, Best Bound, GAP absoluto e relativo", "Presolve, cuts, heurísticas, tempo e tolerâncias", "Solvers HiGHS, CBC, SCIP, OR-Tools e validação da solução"],
    foundation: "MIP mantém restrições/objetivo lineares e mistura domínios de variável. Solvers combinam Branch-and-Bound, cortes, heurísticas e presolve. Incumbente é melhor solução viável; Best Bound é melhor limite restante; GAP mede quão longe a prova pode estar do ótimo.",
    mechanism: "Formule unidades, limites apertados e lógica; exporte modelo; configure seed/tempo/gap; registre status, versão e logs; valide todas as restrições e compare solução a baseline. Decida se gap residual é aceitável pelo valor de negócio.",
    formula: "gap_{rel}=\\frac{|z_{inc}-z_{bound}|}{\\max(\\varepsilon,|z_{inc}|)}\\times100\\%",
    mathExplanation: "Em minimização, incumbente é limite superior e Best Bound é inferior; em maximização, sentidos se invertem. Gap zero prova ótimo dentro das tolerâncias numéricas.",
    bankApplication: "Otimize simultaneamente clientes escolhidos, orçamento contínuo e capacidade inteira por canal. Um resultado 0,5% do bound pode ser excelente se economiza horas e diferença financeira é pequena; a decisão precisa quantificar isso.",
    cases: ["Campanha multicanal com ativação e orçamento.", "Alocação de caixa/recursos com lotes discretos.", "Escolha de solver e limite de tempo em processo diário."],
    pitfalls: ["Reportar solução sem status/gap", "Big-M frouxo e instabilidade", "Assumir que solver encerrou porque provou ótimo"],
    outcomes: ["Distinguir LP/IP/MIP", "Interpretar incumbent/bound/gap", "Configurar e comparar solvers", "Defender qualidade operacional da solução"],
    project: ["otimizador-mip-multicanal", "MIP multicanal com prova de qualidade", "Otimizar seleção, orçamento e capacidade, documentando solver, GAP, Best Bound e trade-offs.", ["Formulação MIP", "Experimentos de solver/tempo/gap", "Relatório executivo e técnico"]],
  },
];
